ALTER TABLE FIDE_USUARIOS_TB
ADD PASSWORD VARCHAR2(255);
/
select * from FIDE_ROLES_TB
/
select * from FIDE_USUARIOS_TB
/
SELECT u.USUARIO_ID, u.ROL_ID, c.CORREO, u.NOMBRE, u.APELLIDO_PATERNO 
FROM FIDE_USUARIOS_TB u
JOIN FIDE_CORREOS_TB c ON u.CORREO_ID = c.CORREO_ID;
/
select * from FIDE_correos_TB
/
UPDATE FIDE_USUARIOS_TB SET PASSWORD = '1234' WHERE USUARIO_ID = 1;
UPDATE FIDE_USUARIOS_TB SET PASSWORD = '1234' WHERE USUARIO_ID = 2;
UPDATE FIDE_USUARIOS_TB SET PASSWORD = '1234' WHERE USUARIO_ID = 7;
UPDATE FIDE_USUARIOS_TB SET PASSWORD = '1234' WHERE USUARIO_ID = 11;
COMMIT;
UPDATE FIDE_USUARIOS_TB SET PASSWORD = '1234' WHERE USUARIO_ID = 16;
COMMIT;
/
SELECT u.USUARIO_ID, u.ROL_ID, u.NOMBRE, cr.CORREO, u.PASSWORD, u.ESTADO_ID
FROM FIDE_USUARIOS_TB u
JOIN FIDE_CORREOS_TB cr ON u.CORREO_ID = cr.CORREO_ID;
