CREATE SEQUENCE FIDE_CITAS_SEQ
  START WITH 1000
  INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_CITAS_BI_TRG
BEFORE INSERT ON FIDE_CITAS_TB
FOR EACH ROW
BEGIN
  IF :NEW.CITA_ID IS NULL THEN
    :NEW.CITA_ID := FIDE_CITAS_SEQ.NEXTVAL;
  END IF;
END;
/
SELECT * FROM fide_citas_tb
SELECT * FROM FIDE_CITAS_TB ORDER BY CITA_ID DESC;
SELECT 
  CITA_ID, CLIENTE_ID, SERVICIO_ID, FECHA_HORA, NOTAS 
FROM FIDE_CITAS_TB
ORDER BY FECHA_HORA DESC;
/
----cambiar pk
ALTER TABLE FIDE_CITAS_TB DROP CONSTRAINT CITAS_CLIENTE_ID_PK;

ALTER TABLE FIDE_CITAS_TB ADD CONSTRAINT CITA_ID_PK PRIMARY KEY (CITA_ID);

/
DELETE FROM FIDE_CITAS_TB;
COMMIT;
/


