ALTER TABLE FIDE_SERVICIOS_TB
ADD IMAGEN_URL VARCHAR2(500);
/
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/facialhidratante.png' WHERE SERVICIO_ID = 1;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/limpiezafacial.jpg' WHERE SERVICIO_ID = 2;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/masajerelajante.jpg' WHERE SERVICIO_ID = 3;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/masajeterapeutico.jpg' WHERE SERVICIO_ID = 4;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/laserfacial.jpg' WHERE SERVICIO_ID = 5;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/manicuraspa.jpg' WHERE SERVICIO_ID = 6;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/pedicuraspa.jpg' WHERE SERVICIO_ID = 7;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/peelingquimico.jpg' WHERE SERVICIO_ID = 8;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/laserco2.jpg' WHERE SERVICIO_ID = 9;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/radiofrecuencia.jpg' WHERE SERVICIO_ID = 10;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/botox.jpg' WHERE SERVICIO_ID = 11;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/rellenolabial.jpg' WHERE SERVICIO_ID = 12;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/facialantiedad.jpg' WHERE SERVICIO_ID = 13;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/hidrofacial.jpg' WHERE SERVICIO_ID = 14;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/microdermoabrasion.jpg' WHERE SERVICIO_ID = 15;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/tratamientoacne.jpg' WHERE SERVICIO_ID = 16;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/peelingdespigmentante.jpg' WHERE SERVICIO_ID = 17;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/tratamientorosacea.jpg' WHERE SERVICIO_ID = 18;
UPDATE FIDE_SERVICIOS_TB SET IMAGEN_URL = 'assets/img/tratamientoestrias.jpg' WHERE SERVICIO_ID = 19;

COMMIT;
/
SELECT * FROM fide_servicios_tb 
