ALTER TABLE FIDE_PRODUCTOS_TB 
ADD IMAGEN_URL VARCHAR2(500);


/
SELECT * FROM fide_productos_tb 
/
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/cremahidratante.jpg' WHERE PRODUCTO_ID = 1;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/serumvc.png' WHERE PRODUCTO_ID = 2;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/protectorsolar.png' WHERE PRODUCTO_ID = 3;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/gelfacial.png' WHERE PRODUCTO_ID = 4;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/antiarrugas.png' WHERE PRODUCTO_ID = 5;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/arcilla.png' WHERE PRODUCTO_ID = 6;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/tonicofacial.png' WHERE PRODUCTO_ID = 7;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/contornoojos.png' WHERE PRODUCTO_ID = 8;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/exfoliantequimico.jpeg' WHERE PRODUCTO_ID = 9;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/aceitefacial.jpg' WHERE PRODUCTO_ID = 10;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/cremacorporal.png' WHERE PRODUCTO_ID = 11;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/bodyoil.png' WHERE PRODUCTO_ID = 12;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/gelreductor.png' WHERE PRODUCTO_ID = 13;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/creamestrias.png' WHERE PRODUCTO_ID = 14;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/kitmani.png' WHERE PRODUCTO_ID = 15;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/esmalte.png' WHERE PRODUCTO_ID = 16;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/cremadepiladora.jpg' WHERE PRODUCTO_ID = 17;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/ceradepi.png' WHERE PRODUCTO_ID = 18;
UPDATE FIDE_PRODUCTOS_TB SET IMAGEN_URL = 'assets/img/shampooprof.jpg' WHERE PRODUCTO_ID = 19;
COMMIT;
/
