create or replace PACKAGE BODY FIDE_ANGELUS_ESTETICA_PKG AS
-- =========================
-- FUNCIONES
-- =========================
FUNCTION FIDE_USUARIOS_OBTENER_NOMBRE_USUARIO_FN(
    P_USUARIO_ID IN NUMBER
) RETURN VARCHAR2 IS
    V_NOMBRE VARCHAR2(300);
BEGIN
    SELECT NOMBRE || ' ' || APELLIDO_PATERNO
    INTO V_NOMBRE
    FROM FIDE_USUARIOS_TB
    WHERE USUARIO_ID = P_USUARIO_ID;

    RETURN V_NOMBRE;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró el usuario con el ID especificado');
        RETURN V_NOMBRE;
END FIDE_USUARIOS_OBTENER_NOMBRE_USUARIO_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_CORREOS_OBTENER_CORREO_USUARIO_FN(
    P_USUARIO_ID IN NUMBER
) RETURN VARCHAR2 IS
    V_CORREO VARCHAR2(255);
BEGIN
    SELECT C.CORREO
    INTO V_CORREO
    FROM FIDE_USUARIOS_TB U
    JOIN FIDE_CORREOS_TB C ON U.CORREO_ID = C.CORREO_ID
    WHERE U.USUARIO_ID = P_USUARIO_ID;

    RETURN V_CORREO;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No fue posible obtener el correo del usuario');
        RETURN V_CORREO;
END FIDE_CORREOS_OBTENER_CORREO_USUARIO_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_DETALLES_FACTURA_TOTAL_FACTURA_FN(
    P_FACTURA_ID IN NUMBER
) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT SUM(PRECIO_UNITARIO * CANTIDAD)
    INTO V_TOTAL
    FROM FIDE_DETALLES_FACTURA_TB
    WHERE FACTURA_ID = P_FACTURA_ID;

    RETURN NVL(V_TOTAL, 0);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró la factura con el ID especificado');
        RETURN V_TOTAL;
END FIDE_DETALLES_FACTURA_TOTAL_FACTURA_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_CITAS_CITA_DISPONIBLE_FN(
    P_FECHA_HORA IN TIMESTAMP,
    P_SERVICIO_ID IN NUMBER
) RETURN NUMBER IS
    V_CANT NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO V_CANT
    FROM FIDE_CITAS_TB
    WHERE FECHA_HORA = P_FECHA_HORA
      AND SERVICIO_ID = P_SERVICIO_ID
      AND ESTADO_ID = 1;

    IF V_CANT = 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No fue posible verificar la disponibilidad de la cita');
        RETURN V_CANT;
END FIDE_CITAS_CITA_DISPONIBLE_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_INVENTARIO_STOCK_PRODUCTO_FN(
    P_PRODUCTO_ID IN NUMBER
) RETURN NUMBER IS
    V_STOCK NUMBER := 0;
BEGIN
    SELECT CANTIDAD
    INTO V_STOCK
    FROM FIDE_INVENTARIO_TB
    WHERE PRODUCTO_ID = P_PRODUCTO_ID;

    RETURN V_STOCK;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró inventario para el producto');
        RETURN V_STOCK;
END FIDE_INVENTARIO_STOCK_PRODUCTO_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_PRODUCTOS_ESTADO_TEXTO_FN(
    P_ESTADO_ID IN NUMBER
) RETURN VARCHAR2 IS
    V_ESTADO VARCHAR2(100);
BEGIN
    SELECT NOMBRE_ESTADO
    INTO V_ESTADO
    FROM FIDE_ESTADOS_TB
    WHERE ESTADO_ID = P_ESTADO_ID;

    RETURN V_ESTADO;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró un estado con el ID especificado');
        RETURN V_ESTADO;
END FIDE_PRODUCTOS_ESTADO_TEXTO_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_FACTURAS_TOTAL_VENTAS_CLIENTE_FN(
    P_CLIENTE_ID IN NUMBER
) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT SUM(TOTAL)
    INTO V_TOTAL
    FROM FIDE_FACTURAS_TB
    WHERE CLIENTE_ID = P_CLIENTE_ID;

    RETURN NVL(V_TOTAL,0);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No fue posible calcular las ventas para el cliente');
        RETURN V_TOTAL;
END FIDE_FACTURAS_TOTAL_VENTAS_CLIENTE_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_CITAS_POR_DIA_FN(
    P_FECHA IN DATE
) RETURN NUMBER IS
    V_CANT NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO V_CANT
    FROM FIDE_CITAS_TB
    WHERE TRUNC(FECHA_HORA) = TRUNC(P_FECHA);

    RETURN V_CANT;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No fue posible obtener las citas del día indicado');
        RETURN V_CANT;
END FIDE_CITAS_POR_DIA_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_DIRECCIONES_DIRECCION_USUARIO_FN(
    P_USUARIO_ID IN NUMBER
) RETURN VARCHAR2 IS
    V_DIR VARCHAR2(500);
BEGIN
    SELECT 
        P.NOMBRE_PROVINCIA || ', ' ||
        C.NOMBRE_CANTON || ', ' ||
        D.NOMBRE_DISTRITO || ' - ' ||
        DIR.DESCRIPCION
    INTO V_DIR
    FROM FIDE_DIRECCIONES_TB DIR
    JOIN FIDE_DISTRITOS_TB D ON DIR.DISTRITO_ID = D.DISTRITO_ID
    JOIN FIDE_CANTONES_TB C ON D.CANTON_ID = C.CANTON_ID
    JOIN FIDE_PROVINCIAS_TB P ON C.PROVINCIA_ID = P.PROVINCIA_ID
    WHERE DIR.USUARIO_ID = P_USUARIO_ID;

    RETURN V_DIR;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No fue posible obtener la dirección del usuario');
        RETURN V_DIR;
END FIDE_DIRECCIONES_DIRECCION_USUARIO_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_SERVICIOS_POR_CATEGORIA_FN(
    P_CATEGORIA_ID IN NUMBER
) RETURN NUMBER IS
    V_CANT NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO V_CANT
    FROM FIDE_SERVICIOS_TB
    WHERE CATEGORIA_ID = P_CATEGORIA_ID;

    RETURN V_CANT;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No se encontraron servicios para la categoría indicada');
        RETURN V_CANT;
END FIDE_SERVICIOS_POR_CATEGORIA_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_PRODUCTOS_POR_PROVEEDOR_FN(
    P_PROVEEDOR_ID IN NUMBER
) RETURN NUMBER IS
    V_CANT NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO V_CANT
    FROM FIDE_PRODUCTOS_TB
    WHERE PROVEEDOR_ID = P_PROVEEDOR_ID;

    RETURN V_CANT;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No se encontraron productos para el proveedor indicado');
        RETURN V_CANT;
END FIDE_PRODUCTOS_POR_PROVEEDOR_FN;
-------------------------------------------------------------------------------------------------
FUNCTION FIDE_CLIENTES_EXISTE_FN(
    P_CLIENTE_ID IN NUMBER
) RETURN NUMBER IS
    V_CANT NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO V_CANT
    FROM FIDE_CLIENTES_TB
    WHERE CLIENTE_ID = P_CLIENTE_ID;

    IF V_CANT > 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No fue posible verificar el cliente indicado');
        RETURN V_CANT;
END FIDE_CLIENTES_EXISTE_FN;
-------------------------------------------------------------------------------------------------
-- =========================
-- PROCEDIMIENTOS
-- =========================
-- =========================
-- PROCEDIMIENTOS PAME
-- =========================
PROCEDURE FIDE_CLIENTES_LISTAR_SP (
  p_cursor OUT SYS_REFCURSOR
) IS
BEGIN
  OPEN p_cursor FOR
    SELECT 
      CLIENTE_ID,
      USUARIO_ID,
      ESTADO_ID,
      PREFERENCIAS,
      HISTORIAL_TRATAMIENTOS
    FROM FIDE_CLIENTES_TB;

  DBMS_OUTPUT.PUT_LINE('Listado de clientes obtenido.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar clientes: ' || SQLERRM);
END FIDE_CLIENTES_LISTAR_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CLIENTES_OBTENER_SP (
  p_cliente_id IN FIDE_CLIENTES_TB.CLIENTE_ID%TYPE,
  p_cursor OUT SYS_REFCURSOR
) IS
BEGIN
  OPEN p_cursor FOR
    SELECT 
      CLIENTE_ID,
      USUARIO_ID,
      ESTADO_ID,
      PREFERENCIAS,
      HISTORIAL_TRATAMIENTOS
    FROM FIDE_CLIENTES_TB
    WHERE CLIENTE_ID = p_cliente_id;
END FIDE_CLIENTES_OBTENER_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_SERVICIOS_OBTENER_TODOS_SP (
  p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN p_cursor FOR
    SELECT 
      SERVICIO_ID,
      ESTADO_ID,
      CATEGORIA_ID,
      NOMBRE,
      DESCRIPCION,
      DURACION,
      PRECIO
    FROM FIDE_SERVICIOS_TB
    WHERE ESTADO_ID = 1  -- opcional, si quieres solo activos
    ORDER BY SERVICIO_ID;

EXCEPTION
  WHEN OTHERS THEN
    RAISE; -- Deja que la API o cliente capture el error real
END FIDE_SERVICIOS_OBTENER_TODOS_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_SERVICIOS_OBTENER_POR_ID_SP (
  p_servicio_id IN FIDE_SERVICIOS_TB.SERVICIO_ID%TYPE,
  p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN p_cursor FOR
    SELECT 
      SERVICIO_ID,
      ESTADO_ID,
      CATEGORIA_ID,
      NOMBRE,
      DESCRIPCION,
      DURACION,
      PRECIO
    FROM FIDE_SERVICIOS_TB
    WHERE SERVICIO_ID = p_servicio_id;

EXCEPTION
  WHEN OTHERS THEN
    RAISE; 
END FIDE_SERVICIOS_OBTENER_POR_ID_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PRODUCTOS_OBTENER_SP (
  p_producto_id   IN  FIDE_PRODUCTOS_TB.PRODUCTO_ID%TYPE,
  p_categoria_id  OUT FIDE_PRODUCTOS_TB.CATEGORIA_ID%TYPE,
  p_estado_id     OUT FIDE_PRODUCTOS_TB.ESTADO_ID%TYPE,
  p_proveedor_id  OUT FIDE_PRODUCTOS_TB.PROVEEDOR_ID%TYPE,
  p_nombre        OUT FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
  p_descripcion   OUT FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
  p_precio        OUT FIDE_PRODUCTOS_TB.PRECIO%TYPE
) IS
BEGIN
  SELECT 
      CATEGORIA_ID,
      ESTADO_ID,
      PROVEEDOR_ID,
      NOMBRE,
      DESCRIPCION,
      PRECIO
  INTO
      p_categoria_id,
      p_estado_id,
      p_proveedor_id,
      p_nombre,
      p_descripcion,
      p_precio
  FROM FIDE_PRODUCTOS_TB
  WHERE PRODUCTO_ID = p_producto_id;

  DBMS_OUTPUT.PUT_LINE('Producto obtenido correctamente.');
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Producto no encontrado.');
    -- Devolver valores nulos
    p_categoria_id := NULL;
    p_estado_id    := NULL;
    p_proveedor_id := NULL;
    p_nombre       := NULL;
    p_descripcion  := NULL;
    p_precio       := NULL;
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al obtener producto: ' || SQLERRM);
END FIDE_PRODUCTOS_OBTENER_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PRODUCTOS_LISTAR_SP (
    p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            PRODUCTO_ID,
            CATEGORIA_ID,
            ESTADO_ID,
            PROVEEDOR_ID,
            NOMBRE,
            DESCRIPCION,
            PRECIO
        FROM FIDE_PRODUCTOS_TB
        ORDER BY NOMBRE; -- opcional, puedes ordenar como quieras

    DBMS_OUTPUT.PUT_LINE('Listado de productos obtenido correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al listar productos: ' || SQLERRM);
END FIDE_PRODUCTOS_LISTAR_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_ESTADOS_TB
-- =========================
PROCEDURE FIDE_ESTADOS_TB_INSERT_SP(
    P_ESTADO_ID     IN FIDE_ESTADOS_TB.ESTADO_ID%TYPE,
    P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_ESTADOS_TB (ESTADO_ID, NOMBRE_ESTADO)
  VALUES (P_ESTADO_ID, P_NOMBRE_ESTADO);
  DBMS_OUTPUT.PUT_LINE('Estado insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar estado.');
END FIDE_ESTADOS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ESTADOS_TB_UPDATE_SP(
    P_ESTADO_ID     IN FIDE_ESTADOS_TB.ESTADO_ID%TYPE,
    P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
) IS
BEGIN
  UPDATE FIDE_ESTADOS_TB
     SET NOMBRE_ESTADO = P_NOMBRE_ESTADO
   WHERE ESTADO_ID = P_ESTADO_ID;
  DBMS_OUTPUT.PUT_LINE('Estado modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar estado.');
END FIDE_ESTADOS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_ROLES_TB
-- =========================
PROCEDURE FIDE_ROLES_TB_INSERT_SP(
    P_ROL_ID     IN FIDE_ROLES_TB.ROL_ID%TYPE,
    P_ESTADO_ID  IN FIDE_ROLES_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_NOMBRE_ROL IN FIDE_ROLES_TB.NOMBRE_ROL%TYPE
) IS
BEGIN
  INSERT INTO FIDE_ROLES_TB (ROL_ID, ESTADO_ID, NOMBRE_ROL)
  VALUES (P_ROL_ID, P_ESTADO_ID, P_NOMBRE_ROL);
  DBMS_OUTPUT.PUT_LINE('Rol insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar rol.');
END FIDE_ROLES_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ROLES_TB_UPDATE_SP(
    P_ROL_ID     IN FIDE_ROLES_TB.ROL_ID%TYPE,
    P_ESTADO_ID  IN FIDE_ROLES_TB.ESTADO_ID%TYPE,
    P_NOMBRE_ROL IN FIDE_ROLES_TB.NOMBRE_ROL%TYPE
) IS
BEGIN
  UPDATE FIDE_ROLES_TB
     SET ESTADO_ID = P_ESTADO_ID,
         NOMBRE_ROL = P_NOMBRE_ROL
   WHERE ROL_ID = P_ROL_ID;
  DBMS_OUTPUT.PUT_LINE('Rol modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar rol.');
END FIDE_ROLES_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ROLES_TB_DELETE_SP(
    P_ROL_ID IN FIDE_ROLES_TB.ROL_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_ROLES_TB
     SET ESTADO_ID = 2
   WHERE ROL_ID = P_ROL_ID;
  DBMS_OUTPUT.PUT_LINE('Rol eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar rol.');
END FIDE_ROLES_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_CORREOS_TB
-- =========================
PROCEDURE FIDE_CORREOS_TB_INSERT_SP(
    P_CORREO_ID IN FIDE_CORREOS_TB.CORREO_ID%TYPE,
    P_ESTADO_ID IN FIDE_CORREOS_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_CORREO    IN FIDE_CORREOS_TB.CORREO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_CORREOS_TB (CORREO_ID, ESTADO_ID, CORREO)
  VALUES (P_CORREO_ID, P_ESTADO_ID, P_CORREO);
  DBMS_OUTPUT.PUT_LINE('Correo insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar correo.');
END FIDE_CORREOS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CORREOS_TB_UPDATE_SP(
    P_CORREO_ID IN FIDE_CORREOS_TB.CORREO_ID%TYPE,
    P_ESTADO_ID IN FIDE_CORREOS_TB.ESTADO_ID%TYPE,
    P_CORREO    IN FIDE_CORREOS_TB.CORREO%TYPE
) IS
BEGIN
  UPDATE FIDE_CORREOS_TB
     SET ESTADO_ID = P_ESTADO_ID,
         CORREO    = P_CORREO
   WHERE CORREO_ID = P_CORREO_ID;
  DBMS_OUTPUT.PUT_LINE('Correo modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar correo.');
END FIDE_CORREOS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CORREOS_TB_DELETE_SP(
    P_CORREO_ID IN FIDE_CORREOS_TB.CORREO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_CORREOS_TB
     SET ESTADO_ID = 2
   WHERE CORREO_ID = P_CORREO_ID;
  DBMS_OUTPUT.PUT_LINE('Correo eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar correo.');
END FIDE_CORREOS_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_TELEFONOS_TB
-- =========================
PROCEDURE FIDE_TELEFONOS_TB_INSERT_SP(
    P_TELEFONO_ID IN FIDE_TELEFONOS_TB.TELEFONO_ID%TYPE,
    P_ESTADO_ID   IN FIDE_TELEFONOS_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_TELEFONO    IN FIDE_TELEFONOS_TB.TELEFONO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_TELEFONOS_TB (TELEFONO_ID, ESTADO_ID, TELEFONO)
  VALUES (P_TELEFONO_ID, P_ESTADO_ID, P_TELEFONO);
  DBMS_OUTPUT.PUT_LINE('Teléfono insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar teléfono.');
END FIDE_TELEFONOS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TELEFONOS_TB_UPDATE_SP(
    P_TELEFONO_ID IN FIDE_TELEFONOS_TB.TELEFONO_ID%TYPE,
    P_ESTADO_ID   IN FIDE_TELEFONOS_TB.ESTADO_ID%TYPE,
    P_TELEFONO    IN FIDE_TELEFONOS_TB.TELEFONO%TYPE
) IS
BEGIN
  UPDATE FIDE_TELEFONOS_TB
     SET ESTADO_ID = P_ESTADO_ID,
         TELEFONO  = P_TELEFONO
   WHERE TELEFONO_ID = P_TELEFONO_ID;
  DBMS_OUTPUT.PUT_LINE('Teléfono modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar teléfono.');
END FIDE_TELEFONOS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TELEFONOS_TB_DELETE_SP(
    P_TELEFONO_ID IN FIDE_TELEFONOS_TB.TELEFONO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_TELEFONOS_TB
     SET ESTADO_ID = 2
   WHERE TELEFONO_ID = P_TELEFONO_ID;
  DBMS_OUTPUT.PUT_LINE('Teléfono eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar teléfono.');
END FIDE_TELEFONOS_TB_DELETE_SP;

-- =========================
-- FIDE_USUARIOS_TB
-- =========================
PROCEDURE FIDE_USUARIOS_TB_INSERT_SP(
    P_USUARIO_ID       IN FIDE_USUARIOS_TB.USUARIO_ID%TYPE,
    P_ROL_ID           IN FIDE_USUARIOS_TB.ROL_ID%TYPE,
    P_CORREO_ID        IN FIDE_USUARIOS_TB.CORREO_ID%TYPE,
    P_TELEFONO_ID      IN FIDE_USUARIOS_TB.TELEFONO_ID%TYPE,
    P_ESTADO_ID        IN FIDE_USUARIOS_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_NOMBRE           IN FIDE_USUARIOS_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_USUARIOS_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_USUARIOS_TB.APELLIDO_MATERNO%TYPE,
    P_FECHA_REGISTRO   IN FIDE_USUARIOS_TB.FECHA_REGISTRO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_USUARIOS_TB
    (USUARIO_ID, ROL_ID, CORREO_ID, TELEFONO_ID, ESTADO_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO)
  VALUES
    (P_USUARIO_ID, P_ROL_ID, P_CORREO_ID, P_TELEFONO_ID, P_ESTADO_ID, P_NOMBRE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_FECHA_REGISTRO);
  DBMS_OUTPUT.PUT_LINE('Usuario insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar usuario.');
END FIDE_USUARIOS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_USUARIOS_TB_UPDATE_SP(
    P_USUARIO_ID       IN FIDE_USUARIOS_TB.USUARIO_ID%TYPE,
    P_ROL_ID           IN FIDE_USUARIOS_TB.ROL_ID%TYPE,
    P_CORREO_ID        IN FIDE_USUARIOS_TB.CORREO_ID%TYPE,
    P_TELEFONO_ID      IN FIDE_USUARIOS_TB.TELEFONO_ID%TYPE,
    P_ESTADO_ID        IN FIDE_USUARIOS_TB.ESTADO_ID%TYPE,
    P_NOMBRE           IN FIDE_USUARIOS_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_USUARIOS_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_USUARIOS_TB.APELLIDO_MATERNO%TYPE,
    P_FECHA_REGISTRO   IN FIDE_USUARIOS_TB.FECHA_REGISTRO%TYPE
) IS
BEGIN
  UPDATE FIDE_USUARIOS_TB
     SET ROL_ID = P_ROL_ID,
         CORREO_ID = P_CORREO_ID,
         TELEFONO_ID = P_TELEFONO_ID,
         ESTADO_ID = P_ESTADO_ID,
         NOMBRE = P_NOMBRE,
         APELLIDO_PATERNO = P_APELLIDO_PATERNO,
         APELLIDO_MATERNO = P_APELLIDO_MATERNO,
         FECHA_REGISTRO = P_FECHA_REGISTRO
   WHERE USUARIO_ID = P_USUARIO_ID;
  DBMS_OUTPUT.PUT_LINE('Usuario modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar usuario.');
END FIDE_USUARIOS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_USUARIOS_TB_DELETE_SP(
    P_USUARIO_ID IN FIDE_USUARIOS_TB.USUARIO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_USUARIOS_TB
     SET ESTADO_ID = 2
   WHERE USUARIO_ID = P_USUARIO_ID;
  DBMS_OUTPUT.PUT_LINE('Usuario eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar usuario.');
END FIDE_USUARIOS_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_CLIENTES_TB
-- =========================
PROCEDURE FIDE_CLIENTES_TB_INSERT_SP(
    P_CLIENTE_ID IN FIDE_CLIENTES_TB.CLIENTE_ID%TYPE,
    P_USUARIO_ID IN FIDE_CLIENTES_TB.USUARIO_ID%TYPE,
    P_ESTADO_ID  IN FIDE_CLIENTES_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_PREFERENCIAS IN FIDE_CLIENTES_TB.PREFERENCIAS%TYPE,
    P_HISTORIAL    IN FIDE_CLIENTES_TB.HISTORIAL_TRATAMIENTOS%TYPE
) IS
BEGIN
  INSERT INTO FIDE_CLIENTES_TB
    (CLIENTE_ID, USUARIO_ID, ESTADO_ID, PREFERENCIAS, HISTORIAL_TRATAMIENTOS)
  VALUES
    (P_CLIENTE_ID, P_USUARIO_ID, P_ESTADO_ID, P_PREFERENCIAS, P_HISTORIAL);
  DBMS_OUTPUT.PUT_LINE('Cliente insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar cliente.');
END FIDE_CLIENTES_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CLIENTES_TB_UPDATE_SP(
    P_CLIENTE_ID IN FIDE_CLIENTES_TB.CLIENTE_ID%TYPE,
    P_USUARIO_ID IN FIDE_CLIENTES_TB.USUARIO_ID%TYPE,
    P_ESTADO_ID  IN FIDE_CLIENTES_TB.ESTADO_ID%TYPE,
    P_PREFERENCIAS IN FIDE_CLIENTES_TB.PREFERENCIAS%TYPE,
    P_HISTORIAL    IN FIDE_CLIENTES_TB.HISTORIAL_TRATAMIENTOS%TYPE
) IS
BEGIN
  UPDATE FIDE_CLIENTES_TB
     SET USUARIO_ID = P_USUARIO_ID,
         ESTADO_ID = P_ESTADO_ID,
         PREFERENCIAS = P_PREFERENCIAS,
         HISTORIAL_TRATAMIENTOS = P_HISTORIAL
   WHERE CLIENTE_ID = P_CLIENTE_ID;
  DBMS_OUTPUT.PUT_LINE('Cliente modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar cliente.');
END FIDE_CLIENTES_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CLIENTES_TB_DELETE_SP(
    P_CLIENTE_ID IN FIDE_CLIENTES_TB.CLIENTE_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_CLIENTES_TB
     SET ESTADO_ID = 2
   WHERE CLIENTE_ID = P_CLIENTE_ID;
  DBMS_OUTPUT.PUT_LINE('Cliente eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar cliente.');
END FIDE_CLIENTES_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_PROVINCIAS_TB
-- =========================
PROCEDURE FIDE_PROVINCIAS_TB_INSERT_SP(
    P_PROVINCIA_ID   IN FIDE_PROVINCIAS_TB.PROVINCIA_ID%TYPE,
    P_ESTADO_ID      IN FIDE_PROVINCIAS_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_NOMBRE         IN FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE
) IS
BEGIN
  INSERT INTO FIDE_PROVINCIAS_TB (PROVINCIA_ID, ESTADO_ID, NOMBRE_PROVINCIA)
  VALUES (P_PROVINCIA_ID, P_ESTADO_ID, P_NOMBRE);
  DBMS_OUTPUT.PUT_LINE('Provincia insertada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar provincia.');
END FIDE_PROVINCIAS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVINCIAS_TB_UPDATE_SP(
    P_PROVINCIA_ID   IN FIDE_PROVINCIAS_TB.PROVINCIA_ID%TYPE,
    P_ESTADO_ID      IN FIDE_PROVINCIAS_TB.ESTADO_ID%TYPE,
    P_NOMBRE         IN FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE
) IS
BEGIN
  UPDATE FIDE_PROVINCIAS_TB
     SET ESTADO_ID = P_ESTADO_ID,
         NOMBRE_PROVINCIA = P_NOMBRE
   WHERE PROVINCIA_ID = P_PROVINCIA_ID;
  DBMS_OUTPUT.PUT_LINE('Provincia modificada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar provincia.');
END FIDE_PROVINCIAS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVINCIAS_TB_DELETE_SP(
    P_PROVINCIA_ID IN FIDE_PROVINCIAS_TB.PROVINCIA_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_PROVINCIAS_TB
     SET ESTADO_ID = 2
   WHERE PROVINCIA_ID = P_PROVINCIA_ID;
  DBMS_OUTPUT.PUT_LINE('Provincia eliminada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar provincia.');
END FIDE_PROVINCIAS_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_CANTONES_TB
-- =========================
PROCEDURE FIDE_CANTONES_TB_INSERT_SP(
    P_CANTON_ID   IN FIDE_CANTONES_TB.CANTON_ID%TYPE,
    P_PROVINCIA_ID IN FIDE_CANTONES_TB.PROVINCIA_ID%TYPE,
    P_ESTADO_ID    IN FIDE_CANTONES_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_NOMBRE       IN FIDE_CANTONES_TB.NOMBRE_CANTON%TYPE
) IS
BEGIN
  INSERT INTO FIDE_CANTONES_TB (CANTON_ID, PROVINCIA_ID, ESTADO_ID, NOMBRE_CANTON)
  VALUES (P_CANTON_ID, P_PROVINCIA_ID, P_ESTADO_ID, P_NOMBRE);
  DBMS_OUTPUT.PUT_LINE('Cantón insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar cantón.');
END FIDE_CANTONES_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CANTONES_TB_UPDATE_SP(
    P_CANTON_ID   IN FIDE_CANTONES_TB.CANTON_ID%TYPE,
    P_PROVINCIA_ID IN FIDE_CANTONES_TB.PROVINCIA_ID%TYPE,
    P_ESTADO_ID    IN FIDE_CANTONES_TB.ESTADO_ID%TYPE,
    P_NOMBRE       IN FIDE_CANTONES_TB.NOMBRE_CANTON%TYPE
) IS
BEGIN
  UPDATE FIDE_CANTONES_TB
     SET PROVINCIA_ID = P_PROVINCIA_ID,
         ESTADO_ID    = P_ESTADO_ID,
         NOMBRE_CANTON = P_NOMBRE
   WHERE CANTON_ID = P_CANTON_ID;
  DBMS_OUTPUT.PUT_LINE('Cantón modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar cantón.');
END FIDE_CANTONES_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CANTONES_TB_DELETE_SP(
    P_CANTON_ID IN FIDE_CANTONES_TB.CANTON_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_CANTONES_TB
     SET ESTADO_ID = 2
   WHERE CANTON_ID = P_CANTON_ID;
  DBMS_OUTPUT.PUT_LINE('Cantón eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar cantón.');
END FIDE_CANTONES_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_DISTRITOS_TB
-- =========================
PROCEDURE FIDE_DISTRITOS_TB_INSERT_SP(
    P_DISTRITO_ID IN FIDE_DISTRITOS_TB.DISTRITO_ID%TYPE,
    P_CANTON_ID   IN FIDE_DISTRITOS_TB.CANTON_ID%TYPE,
    P_ESTADO_ID   IN FIDE_DISTRITOS_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_NOMBRE      IN FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_DISTRITOS_TB (DISTRITO_ID, CANTON_ID, ESTADO_ID, NOMBRE_DISTRITO)
  VALUES (P_DISTRITO_ID, P_CANTON_ID, P_ESTADO_ID, P_NOMBRE);
  DBMS_OUTPUT.PUT_LINE('Distrito insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar distrito.');
END FIDE_DISTRITOS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DISTRITOS_TB_UPDATE_SP(
    P_DISTRITO_ID IN FIDE_DISTRITOS_TB.DISTRITO_ID%TYPE,
    P_CANTON_ID   IN FIDE_DISTRITOS_TB.CANTON_ID%TYPE,
    P_ESTADO_ID   IN FIDE_DISTRITOS_TB.ESTADO_ID%TYPE,
    P_NOMBRE      IN FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE
) IS
BEGIN
  UPDATE FIDE_DISTRITOS_TB
     SET CANTON_ID = P_CANTON_ID,
         ESTADO_ID = P_ESTADO_ID,
         NOMBRE_DISTRITO = P_NOMBRE
   WHERE DISTRITO_ID = P_DISTRITO_ID;
  DBMS_OUTPUT.PUT_LINE('Distrito modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar distrito.');
END FIDE_DISTRITOS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DISTRITOS_TB_DELETE_SP(
    P_DISTRITO_ID IN FIDE_DISTRITOS_TB.DISTRITO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_DISTRITOS_TB
     SET ESTADO_ID = 2
   WHERE DISTRITO_ID = P_DISTRITO_ID;
  DBMS_OUTPUT.PUT_LINE('Distrito eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar distrito.');
END FIDE_DISTRITOS_TB_DELETE_SP;

-- =========================
-- FIDE_DIRECCIONES_TB
-- =========================
PROCEDURE FIDE_DIRECCIONES_TB_INSERT_SP(
    P_USUARIO_ID  IN FIDE_DIRECCIONES_TB.USUARIO_ID%TYPE,
    P_DISTRITO_ID IN FIDE_DIRECCIONES_TB.DISTRITO_ID%TYPE,
    P_ESTADO_ID   IN FIDE_DIRECCIONES_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_DESCRIPCION IN FIDE_DIRECCIONES_TB.DESCRIPCION%TYPE
) IS
BEGIN
  INSERT INTO FIDE_DIRECCIONES_TB
    (USUARIO_ID, DISTRITO_ID, ESTADO_ID, DESCRIPCION)
  VALUES
    (P_USUARIO_ID, P_DISTRITO_ID, P_ESTADO_ID, P_DESCRIPCION);
  DBMS_OUTPUT.PUT_LINE('Dirección insertada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar dirección.');
END FIDE_DIRECCIONES_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DIRECCIONES_TB_UPDATE_SP(
    P_USUARIO_ID  IN FIDE_DIRECCIONES_TB.USUARIO_ID%TYPE,
    P_DISTRITO_ID IN FIDE_DIRECCIONES_TB.DISTRITO_ID%TYPE,
    P_ESTADO_ID   IN FIDE_DIRECCIONES_TB.ESTADO_ID%TYPE,
    P_DESCRIPCION IN FIDE_DIRECCIONES_TB.DESCRIPCION%TYPE
) IS
BEGIN
  UPDATE FIDE_DIRECCIONES_TB
     SET ESTADO_ID = P_ESTADO_ID,
         DESCRIPCION = P_DESCRIPCION
   WHERE USUARIO_ID = P_USUARIO_ID AND DISTRITO_ID = P_DISTRITO_ID;
  DBMS_OUTPUT.PUT_LINE('Dirección modificada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar dirección.');
END FIDE_DIRECCIONES_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DIRECCIONES_TB_DELETE_SP(
    P_USUARIO_ID  IN FIDE_DIRECCIONES_TB.USUARIO_ID%TYPE,
    P_DISTRITO_ID IN FIDE_DIRECCIONES_TB.DISTRITO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_DIRECCIONES_TB
     SET ESTADO_ID = 2
   WHERE USUARIO_ID = P_USUARIO_ID AND DISTRITO_ID = P_DISTRITO_ID;
  DBMS_OUTPUT.PUT_LINE('Dirección eliminada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar dirección.');
END FIDE_DIRECCIONES_TB_DELETE_SP;

-- =========================
-- FIDE_CATEGORIAS_TB
-- =========================
PROCEDURE FIDE_CATEGORIAS_TB_INSERT_SP(
    P_CATEGORIA_ID IN FIDE_CATEGORIAS_TB.CATEGORIA_ID%TYPE,
    P_ESTADO_ID    IN FIDE_CATEGORIAS_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_NOMBRE       IN FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE
) IS
BEGIN
  INSERT INTO FIDE_CATEGORIAS_TB (CATEGORIA_ID, ESTADO_ID, NOMBRE_CATEGORIA)
  VALUES (P_CATEGORIA_ID, P_ESTADO_ID, P_NOMBRE);
  DBMS_OUTPUT.PUT_LINE('Categoría insertada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar categoría.');
END FIDE_CATEGORIAS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CATEGORIAS_TB_UPDATE_SP(
    P_CATEGORIA_ID IN FIDE_CATEGORIAS_TB.CATEGORIA_ID%TYPE,
    P_ESTADO_ID    IN FIDE_CATEGORIAS_TB.ESTADO_ID%TYPE,
    P_NOMBRE       IN FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE
) IS
BEGIN
  UPDATE FIDE_CATEGORIAS_TB
     SET ESTADO_ID = P_ESTADO_ID,
         NOMBRE_CATEGORIA = P_NOMBRE
   WHERE CATEGORIA_ID = P_CATEGORIA_ID;
  DBMS_OUTPUT.PUT_LINE('Categoría modificada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar categoría.');
END FIDE_CATEGORIAS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CATEGORIAS_TB_DELETE_SP(
    P_CATEGORIA_ID IN FIDE_CATEGORIAS_TB.CATEGORIA_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_CATEGORIAS_TB
     SET ESTADO_ID = 2
   WHERE CATEGORIA_ID = P_CATEGORIA_ID;
  DBMS_OUTPUT.PUT_LINE('Categoría eliminada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar categoría.');
END FIDE_CATEGORIAS_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_SERVICIOS_TB
-- =========================
PROCEDURE FIDE_SERVICIOS_TB_INSERT_SP(
    P_SERVICIO_ID IN FIDE_SERVICIOS_TB.SERVICIO_ID%TYPE,
    P_ESTADO_ID   IN FIDE_SERVICIOS_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_CATEGORIA_ID IN FIDE_SERVICIOS_TB.CATEGORIA_ID%TYPE,
    P_NOMBRE      IN FIDE_SERVICIOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
    P_DURACION    IN FIDE_SERVICIOS_TB.DURACION%TYPE,
    P_PRECIO      IN FIDE_SERVICIOS_TB.PRECIO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_SERVICIOS_TB
    (SERVICIO_ID, ESTADO_ID, CATEGORIA_ID, NOMBRE, DESCRIPCION, DURACION, PRECIO)
  VALUES
    (P_SERVICIO_ID, P_ESTADO_ID, P_CATEGORIA_ID, P_NOMBRE, P_DESCRIPCION, P_DURACION, P_PRECIO);
  DBMS_OUTPUT.PUT_LINE('Servicio insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar servicio.');
END FIDE_SERVICIOS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_SERVICIOS_TB_UPDATE_SP(
    P_SERVICIO_ID IN FIDE_SERVICIOS_TB.SERVICIO_ID%TYPE,
    P_ESTADO_ID   IN FIDE_SERVICIOS_TB.ESTADO_ID%TYPE,
    P_CATEGORIA_ID IN FIDE_SERVICIOS_TB.CATEGORIA_ID%TYPE,
    P_NOMBRE      IN FIDE_SERVICIOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
    P_DURACION    IN FIDE_SERVICIOS_TB.DURACION%TYPE,
    P_PRECIO      IN FIDE_SERVICIOS_TB.PRECIO%TYPE
) IS
BEGIN
  UPDATE FIDE_SERVICIOS_TB
     SET ESTADO_ID = P_ESTADO_ID,
         CATEGORIA_ID = P_CATEGORIA_ID,
         NOMBRE = P_NOMBRE,
         DESCRIPCION = P_DESCRIPCION,
         DURACION = P_DURACION,
         PRECIO = P_PRECIO
   WHERE SERVICIO_ID = P_SERVICIO_ID;
  DBMS_OUTPUT.PUT_LINE('Servicio modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar servicio.');
END FIDE_SERVICIOS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_SERVICIOS_TB_DELETE_SP(
    P_SERVICIO_ID IN FIDE_SERVICIOS_TB.SERVICIO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_SERVICIOS_TB
     SET ESTADO_ID = 2
   WHERE SERVICIO_ID = P_SERVICIO_ID;
  DBMS_OUTPUT.PUT_LINE('Servicio eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar servicio.');
END FIDE_SERVICIOS_TB_DELETE_SP;

-- =========================
-- FIDE_CITAS_TB
-- =========================
PROCEDURE FIDE_CITAS_TB_INSERT_SP(
    P_CITA_ID     IN FIDE_CITAS_TB.CITA_ID%TYPE,
    P_CLIENTE_ID  IN FIDE_CITAS_TB.CLIENTE_ID%TYPE,
    P_SERVICIO_ID IN FIDE_CITAS_TB.SERVICIO_ID%TYPE,
    P_ESTADO_ID   IN FIDE_CITAS_TB.ESTADO_ID%TYPE DEFAULT 3,
    P_FECHA_HORA  IN FIDE_CITAS_TB.FECHA_HORA%TYPE,
    P_NOTAS       IN FIDE_CITAS_TB.NOTAS%TYPE
) IS
BEGIN
  INSERT INTO FIDE_CITAS_TB
    (CITA_ID, CLIENTE_ID, SERVICIO_ID, ESTADO_ID, FECHA_HORA, NOTAS)
  VALUES
    (P_CITA_ID, P_CLIENTE_ID, P_SERVICIO_ID, P_ESTADO_ID, P_FECHA_HORA, P_NOTAS);
  DBMS_OUTPUT.PUT_LINE('Cita insertada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar cita.');
END FIDE_CITAS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CITAS_TB_UPDATE_SP(
    P_CITA_ID     IN FIDE_CITAS_TB.CITA_ID%TYPE,
    P_CLIENTE_ID  IN FIDE_CITAS_TB.CLIENTE_ID%TYPE,
    P_SERVICIO_ID IN FIDE_CITAS_TB.SERVICIO_ID%TYPE,
    P_ESTADO_ID   IN FIDE_CITAS_TB.ESTADO_ID%TYPE,
    P_FECHA_HORA  IN FIDE_CITAS_TB.FECHA_HORA%TYPE,
    P_NOTAS       IN FIDE_CITAS_TB.NOTAS%TYPE
) IS
BEGIN
  UPDATE FIDE_CITAS_TB
     SET CLIENTE_ID = P_CLIENTE_ID,
         SERVICIO_ID = P_SERVICIO_ID,
         ESTADO_ID = P_ESTADO_ID,
         FECHA_HORA = P_FECHA_HORA,
         NOTAS = P_NOTAS
   WHERE CITA_ID = P_CITA_ID;
  DBMS_OUTPUT.PUT_LINE('Cita modificada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar cita.');
END FIDE_CITAS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CITAS_TB_DELETE_SP(
    P_CITA_ID IN FIDE_CITAS_TB.CITA_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_CITAS_TB
     SET ESTADO_ID = 5
   WHERE CITA_ID = P_CITA_ID;
  DBMS_OUTPUT.PUT_LINE('Cita eliminada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar cita.');
END FIDE_CITAS_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_PROVEEDORES_TB
-- =========================
PROCEDURE FIDE_PROVEEDORES_TB_INSERT_SP(
    P_PROVEEDOR_ID IN FIDE_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
    P_ESTADO_ID    IN FIDE_PROVEEDORES_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_TELEFONO_ID  IN FIDE_PROVEEDORES_TB.TELEFONO_ID%TYPE,
    P_NOMBRE       IN FIDE_PROVEEDORES_TB.NOMBRE%TYPE,
    P_CONTACTO     IN FIDE_PROVEEDORES_TB.CONTACTO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_PROVEEDORES_TB
    (PROVEEDOR_ID, ESTADO_ID, TELEFONO_ID, NOMBRE, CONTACTO)
  VALUES
    (P_PROVEEDOR_ID, P_ESTADO_ID, P_TELEFONO_ID, P_NOMBRE, P_CONTACTO);
  DBMS_OUTPUT.PUT_LINE('Proveedor insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar proveedor.');
END FIDE_PROVEEDORES_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVEEDORES_TB_UPDATE_SP(
    P_PROVEEDOR_ID IN FIDE_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
    P_ESTADO_ID    IN FIDE_PROVEEDORES_TB.ESTADO_ID%TYPE,
    P_TELEFONO_ID  IN FIDE_PROVEEDORES_TB.TELEFONO_ID%TYPE,
    P_NOMBRE       IN FIDE_PROVEEDORES_TB.NOMBRE%TYPE,
    P_CONTACTO     IN FIDE_PROVEEDORES_TB.CONTACTO%TYPE
) IS
BEGIN
  UPDATE FIDE_PROVEEDORES_TB
     SET ESTADO_ID = P_ESTADO_ID,
         TELEFONO_ID = P_TELEFONO_ID,
         NOMBRE = P_NOMBRE,
         CONTACTO = P_CONTACTO
   WHERE PROVEEDOR_ID = P_PROVEEDOR_ID;
  DBMS_OUTPUT.PUT_LINE('Proveedor modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar proveedor.');
END FIDE_PROVEEDORES_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVEEDORES_TB_DELETE_SP(
    P_PROVEEDOR_ID IN FIDE_PROVEEDORES_TB.PROVEEDOR_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_PROVEEDORES_TB
     SET ESTADO_ID = 2
   WHERE PROVEEDOR_ID = P_PROVEEDOR_ID;
  DBMS_OUTPUT.PUT_LINE('Proveedor eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar proveedor.');
END FIDE_PROVEEDORES_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_PRODUCTOS_TB
-- =========================
PROCEDURE FIDE_PRODUCTOS_TB_INSERT_SP(
    P_PRODUCTO_ID IN FIDE_PRODUCTOS_TB.PRODUCTO_ID%TYPE,
    P_CATEGORIA_ID IN FIDE_PRODUCTOS_TB.CATEGORIA_ID%TYPE,
    P_ESTADO_ID    IN FIDE_PRODUCTOS_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_PROVEEDOR_ID IN FIDE_PRODUCTOS_TB.PROVEEDOR_ID%TYPE,
    P_NOMBRE       IN FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION  IN FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
    P_PRECIO       IN FIDE_PRODUCTOS_TB.PRECIO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_PRODUCTOS_TB
    (PRODUCTO_ID, CATEGORIA_ID, ESTADO_ID, PROVEEDOR_ID, NOMBRE, DESCRIPCION, PRECIO)
  VALUES
    (P_PRODUCTO_ID, P_CATEGORIA_ID, P_ESTADO_ID, P_PROVEEDOR_ID, P_NOMBRE, P_DESCRIPCION, P_PRECIO);
  DBMS_OUTPUT.PUT_LINE('Producto insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar producto.');
END FIDE_PRODUCTOS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PRODUCTOS_TB_UPDATE_SP(
    P_PRODUCTO_ID IN FIDE_PRODUCTOS_TB.PRODUCTO_ID%TYPE,
    P_CATEGORIA_ID IN FIDE_PRODUCTOS_TB.CATEGORIA_ID%TYPE,
    P_ESTADO_ID    IN FIDE_PRODUCTOS_TB.ESTADO_ID%TYPE,
    P_PROVEEDOR_ID IN FIDE_PRODUCTOS_TB.PROVEEDOR_ID%TYPE,
    P_NOMBRE       IN FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION  IN FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
    P_PRECIO       IN FIDE_PRODUCTOS_TB.PRECIO%TYPE
) IS
BEGIN
  UPDATE FIDE_PRODUCTOS_TB
     SET CATEGORIA_ID = P_CATEGORIA_ID,
         ESTADO_ID = P_ESTADO_ID,
         PROVEEDOR_ID = P_PROVEEDOR_ID,
         NOMBRE = P_NOMBRE,
         DESCRIPCION = P_DESCRIPCION,
         PRECIO = P_PRECIO
   WHERE PRODUCTO_ID = P_PRODUCTO_ID;
  DBMS_OUTPUT.PUT_LINE('Producto modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar producto.');
END FIDE_PRODUCTOS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PRODUCTOS_TB_DELETE_SP(
    P_PRODUCTO_ID IN FIDE_PRODUCTOS_TB.PRODUCTO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_PRODUCTOS_TB
     SET ESTADO_ID = 2
   WHERE PRODUCTO_ID = P_PRODUCTO_ID;
  DBMS_OUTPUT.PUT_LINE('Producto eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar producto.');
END FIDE_PRODUCTOS_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_INVENTARIO_TB
-- =========================
PROCEDURE FIDE_INVENTARIO_TB_INSERT_SP(
    P_INVENTARIO_ID IN FIDE_INVENTARIO_TB.INVENTARIO_ID%TYPE,
    P_PRODUCTO_ID   IN FIDE_INVENTARIO_TB.PRODUCTO_ID%TYPE,
    P_ESTADO_ID     IN FIDE_INVENTARIO_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_CANTIDAD      IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
    P_FECHA_ACT     IN FIDE_INVENTARIO_TB.FECHA_ACTUALIZACION%TYPE
) IS
BEGIN
  INSERT INTO FIDE_INVENTARIO_TB
    (INVENTARIO_ID, PRODUCTO_ID, ESTADO_ID, CANTIDAD, FECHA_ACTUALIZACION)
  VALUES
    (P_INVENTARIO_ID, P_PRODUCTO_ID, P_ESTADO_ID, P_CANTIDAD, P_FECHA_ACT);
  DBMS_OUTPUT.PUT_LINE('Inventario insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar inventario.');
END FIDE_INVENTARIO_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INVENTARIO_TB_UPDATE_SP(
    P_INVENTARIO_ID IN FIDE_INVENTARIO_TB.INVENTARIO_ID%TYPE,
    P_PRODUCTO_ID   IN FIDE_INVENTARIO_TB.PRODUCTO_ID%TYPE,
    P_ESTADO_ID     IN FIDE_INVENTARIO_TB.ESTADO_ID%TYPE,
    P_CANTIDAD      IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
    P_FECHA_ACT     IN FIDE_INVENTARIO_TB.FECHA_ACTUALIZACION%TYPE
) IS
BEGIN
  UPDATE FIDE_INVENTARIO_TB
     SET PRODUCTO_ID = P_PRODUCTO_ID,
         ESTADO_ID = P_ESTADO_ID,
         CANTIDAD = P_CANTIDAD,
         FECHA_ACTUALIZACION = P_FECHA_ACT
   WHERE INVENTARIO_ID = P_INVENTARIO_ID;
  DBMS_OUTPUT.PUT_LINE('Inventario modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar inventario.');
END FIDE_INVENTARIO_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INVENTARIO_TB_DELETE_SP(
    P_INVENTARIO_ID IN FIDE_INVENTARIO_TB.INVENTARIO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_INVENTARIO_TB
     SET ESTADO_ID = 2
   WHERE INVENTARIO_ID = P_INVENTARIO_ID;
  DBMS_OUTPUT.PUT_LINE('Inventario eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar inventario.');
END FIDE_INVENTARIO_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_METODOS_PAGO_TB
-- =========================
PROCEDURE FIDE_METODOS_PAGO_TB_INSERT_SP(
    P_METODO_PAGO_ID IN FIDE_METODOS_PAGO_TB.METODO_PAGO_ID%TYPE,
    P_ESTADO_ID      IN FIDE_METODOS_PAGO_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_NOMBRE_METODO  IN FIDE_METODOS_PAGO_TB.NOMBRE_METODO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_METODOS_PAGO_TB
    (METODO_PAGO_ID, ESTADO_ID, NOMBRE_METODO)
  VALUES
    (P_METODO_PAGO_ID, P_ESTADO_ID, P_NOMBRE_METODO);
  DBMS_OUTPUT.PUT_LINE('Método de pago insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar método de pago.');
END FIDE_METODOS_PAGO_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_METODOS_PAGO_TB_UPDATE_SP(
    P_METODO_PAGO_ID IN FIDE_METODOS_PAGO_TB.METODO_PAGO_ID%TYPE,
    P_ESTADO_ID      IN FIDE_METODOS_PAGO_TB.ESTADO_ID%TYPE,
    P_NOMBRE_METODO  IN FIDE_METODOS_PAGO_TB.NOMBRE_METODO%TYPE
) IS
BEGIN
  UPDATE FIDE_METODOS_PAGO_TB
     SET ESTADO_ID = P_ESTADO_ID,
         NOMBRE_METODO = P_NOMBRE_METODO
   WHERE METODO_PAGO_ID = P_METODO_PAGO_ID;
  DBMS_OUTPUT.PUT_LINE('Método de pago modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar método de pago.');
END FIDE_METODOS_PAGO_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_METODOS_PAGO_TB_DELETE_SP(
    P_METODO_PAGO_ID IN FIDE_METODOS_PAGO_TB.METODO_PAGO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_METODOS_PAGO_TB
     SET ESTADO_ID = 2
   WHERE METODO_PAGO_ID = P_METODO_PAGO_ID;
  DBMS_OUTPUT.PUT_LINE('Método de pago eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar método de pago.');
END FIDE_METODOS_PAGO_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_FACTURAS_TB
-- =========================
PROCEDURE FIDE_FACTURAS_TB_INSERT_SP(
    P_FACTURA_ID     IN FIDE_FACTURAS_TB.FACTURA_ID%TYPE,
    P_CLIENTE_ID     IN FIDE_FACTURAS_TB.CLIENTE_ID%TYPE,
    P_ESTADO_ID      IN FIDE_FACTURAS_TB.ESTADO_ID%TYPE DEFAULT 8,
    P_METODO_PAGO_ID IN FIDE_FACTURAS_TB.METODO_PAGO_ID%TYPE,
    P_FECHA          IN FIDE_FACTURAS_TB.FECHA%TYPE,
    P_IMPUESTOS      IN FIDE_FACTURAS_TB.IMPUESTOS%TYPE,
    P_TOTAL          IN FIDE_FACTURAS_TB.TOTAL%TYPE
) IS
BEGIN
  INSERT INTO FIDE_FACTURAS_TB
    (FACTURA_ID, CLIENTE_ID, ESTADO_ID, METODO_PAGO_ID, FECHA, IMPUESTOS, TOTAL)
  VALUES
    (P_FACTURA_ID, P_CLIENTE_ID, P_ESTADO_ID, P_METODO_PAGO_ID, P_FECHA, P_IMPUESTOS, P_TOTAL);
  DBMS_OUTPUT.PUT_LINE('Factura insertada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar factura.');
END FIDE_FACTURAS_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_FACTURAS_TB_UPDATE_SP(
    P_FACTURA_ID     IN FIDE_FACTURAS_TB.FACTURA_ID%TYPE,
    P_CLIENTE_ID     IN FIDE_FACTURAS_TB.CLIENTE_ID%TYPE,
    P_ESTADO_ID      IN FIDE_FACTURAS_TB.ESTADO_ID%TYPE,
    P_METODO_PAGO_ID IN FIDE_FACTURAS_TB.METODO_PAGO_ID%TYPE,
    P_FECHA          IN FIDE_FACTURAS_TB.FECHA%TYPE,
    P_IMPUESTOS      IN FIDE_FACTURAS_TB.IMPUESTOS%TYPE,
    P_TOTAL          IN FIDE_FACTURAS_TB.TOTAL%TYPE
) IS
BEGIN
  UPDATE FIDE_FACTURAS_TB
     SET CLIENTE_ID = P_CLIENTE_ID,
         ESTADO_ID = P_ESTADO_ID,
         METODO_PAGO_ID = P_METODO_PAGO_ID,
         FECHA = P_FECHA,
         IMPUESTOS = P_IMPUESTOS,
         TOTAL = P_TOTAL
   WHERE FACTURA_ID = P_FACTURA_ID;
  DBMS_OUTPUT.PUT_LINE('Factura modificada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar factura.');
END FIDE_FACTURAS_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_FACTURAS_TB_DELETE_SP(
    P_FACTURA_ID IN FIDE_FACTURAS_TB.FACTURA_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_FACTURAS_TB
     SET ESTADO_ID = 5
   WHERE FACTURA_ID = P_FACTURA_ID;
  DBMS_OUTPUT.PUT_LINE('Factura eliminada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar factura.');
END FIDE_FACTURAS_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_DETALLES_FACTURA_TB
-- =========================
PROCEDURE FIDE_DETALLES_FACTURA_TB_INSERT_SP(
    P_DETALLE_ID    IN FIDE_DETALLES_FACTURA_TB.DETALLE_ID%TYPE,
    P_FACTURA_ID    IN FIDE_DETALLES_FACTURA_TB.FACTURA_ID%TYPE,
    P_SERVICIO_ID   IN FIDE_DETALLES_FACTURA_TB.SERVICIO_ID%TYPE,
    P_PRODUCTO_ID   IN FIDE_DETALLES_FACTURA_TB.PRODUCTO_ID%TYPE,
    P_ESTADO_ID     IN FIDE_DETALLES_FACTURA_TB.ESTADO_ID%TYPE DEFAULT 1,
    P_PRECIO_UNIT   IN FIDE_DETALLES_FACTURA_TB.PRECIO_UNITARIO%TYPE,
    P_CANTIDAD      IN FIDE_DETALLES_FACTURA_TB.CANTIDAD%TYPE
) IS
BEGIN
  INSERT INTO FIDE_DETALLES_FACTURA_TB
    (DETALLE_ID, FACTURA_ID, SERVICIO_ID, PRODUCTO_ID, ESTADO_ID, PRECIO_UNITARIO, CANTIDAD)
  VALUES
    (P_DETALLE_ID, P_FACTURA_ID, P_SERVICIO_ID, P_PRODUCTO_ID, P_ESTADO_ID, P_PRECIO_UNIT, P_CANTIDAD);
  DBMS_OUTPUT.PUT_LINE('Detalle de factura insertado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar detalle de factura.');
END FIDE_DETALLES_FACTURA_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DETALLES_FACTURA_TB_UPDATE_SP(
    P_DETALLE_ID    IN FIDE_DETALLES_FACTURA_TB.DETALLE_ID%TYPE,
    P_FACTURA_ID    IN FIDE_DETALLES_FACTURA_TB.FACTURA_ID%TYPE,
    P_SERVICIO_ID   IN FIDE_DETALLES_FACTURA_TB.SERVICIO_ID%TYPE,
    P_PRODUCTO_ID   IN FIDE_DETALLES_FACTURA_TB.PRODUCTO_ID%TYPE,
    P_ESTADO_ID     IN FIDE_DETALLES_FACTURA_TB.ESTADO_ID%TYPE,
    P_PRECIO_UNIT   IN FIDE_DETALLES_FACTURA_TB.PRECIO_UNITARIO%TYPE,
    P_CANTIDAD      IN FIDE_DETALLES_FACTURA_TB.CANTIDAD%TYPE
) IS
BEGIN
  UPDATE FIDE_DETALLES_FACTURA_TB
     SET FACTURA_ID = P_FACTURA_ID,
         SERVICIO_ID = P_SERVICIO_ID,
         PRODUCTO_ID = P_PRODUCTO_ID,
         ESTADO_ID = P_ESTADO_ID,
         PRECIO_UNITARIO = P_PRECIO_UNIT,
         CANTIDAD = P_CANTIDAD
   WHERE DETALLE_ID = P_DETALLE_ID;
  DBMS_OUTPUT.PUT_LINE('Detalle de factura modificado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar detalle de factura.');
END FIDE_DETALLES_FACTURA_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DETALLES_FACTURA_TB_DELETE_SP(
    P_DETALLE_ID IN FIDE_DETALLES_FACTURA_TB.DETALLE_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_DETALLES_FACTURA_TB
     SET ESTADO_ID = 2
   WHERE DETALLE_ID = P_DETALLE_ID;
  DBMS_OUTPUT.PUT_LINE('Detalle de factura eliminado.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al eliminar detalle de factura.');
END FIDE_DETALLES_FACTURA_TB_DELETE_SP;
-------------------------------------------------------------------------------------------------
-- =========================
-- FIDE_DIRECCIONES_PROVEEDORES_TB
-- =========================
PROCEDURE FIDE_DIRECCIONES_PROVEEDORES_TB_INSERT_SP(
    P_PROVEEDOR_ID IN FIDE_DIRECCIONES_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
    P_DISTRITO_ID  IN FIDE_DIRECCIONES_PROVEEDORES_TB.DISTRITO_ID%TYPE
) IS
BEGIN
  INSERT INTO FIDE_DIRECCIONES_PROVEEDORES_TB (PROVEEDOR_ID, DISTRITO_ID)
  VALUES (P_PROVEEDOR_ID, P_DISTRITO_ID);
  DBMS_OUTPUT.PUT_LINE('Dirección de proveedor insertada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar dirección de proveedor.');
END FIDE_DIRECCIONES_PROVEEDORES_TB_INSERT_SP;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DIRECCIONES_PROVEEDORES_TB_UPDATE_SP(
    P_PROVEEDOR_ID IN FIDE_DIRECCIONES_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
    P_DISTRITO_ID  IN FIDE_DIRECCIONES_PROVEEDORES_TB.DISTRITO_ID%TYPE,
    P_NUEVO_PROVEEDOR_ID IN FIDE_DIRECCIONES_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
    P_NUEVO_DISTRITO_ID  IN FIDE_DIRECCIONES_PROVEEDORES_TB.DISTRITO_ID%TYPE
) IS
BEGIN
  UPDATE FIDE_DIRECCIONES_PROVEEDORES_TB
     SET PROVEEDOR_ID = P_NUEVO_PROVEEDOR_ID,
         DISTRITO_ID  = P_NUEVO_DISTRITO_ID
   WHERE PROVEEDOR_ID = P_PROVEEDOR_ID
     AND DISTRITO_ID  = P_DISTRITO_ID;
  DBMS_OUTPUT.PUT_LINE('Dirección de proveedor modificada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al modificar dirección de proveedor.');
END FIDE_DIRECCIONES_PROVEEDORES_TB_UPDATE_SP;
-------------------------------------------------------------------------------------------------
END FIDE_ANGELUS_ESTETICA_PKG;