--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package FIDE_ANGELUS_ESTETICA_PKG
--------------------------------------------------------

CREATE OR REPLACE EDITIONABLE PACKAGE "ANGELUS_ESTETICA"."FIDE_ANGELUS_ESTETICA_PKG" AS

-- =========================
-- FUNCIONES
-- =========================

-- Obtiene el nombre completo de un usuario por ID
FUNCTION USUARIOS_OBTENER_NOMBRE_USUARIO_FN(
    P_USUARIO_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene las citas pendientes
FUNCTION CITAS_OBTENER_PENDIENTES_FN 
RETURN VARCHAR2;

-- Obtiene productos con stock bajo
FUNCTION INVENTARIO_OBTENER_BAJO_STOCK_FN(
    P_MINIMO NUMBER DEFAULT 10
) RETURN VARCHAR2;

-- Obtiene citas programadas para el día actual
FUNCTION CITAS_OBTENER_DEL_DIA_FN
RETURN VARCHAR2;

-- Genera secuencia para facturas
FUNCTION FACTURAS_TB_SECUENCIA_FN
RETURN NUMBER;

-- Lista proveedores activos
FUNCTION PROVEEDORES_LISTAR_FN
RETURN VARCHAR2;

-- Lista usuarios activos
FUNCTION USUARIOS_LISTAR_ACTIVOS_FN
RETURN VARCHAR2;

-- Lista clientes registrados
FUNCTION CLIENTES_LISTAR_FN
RETURN VARCHAR2;

-- Lista servicios activos
FUNCTION SERVICIOS_LISTAR_ACTIVOS_FN
RETURN VARCHAR2;

-- Lista productos activos
FUNCTION PRODUCTOS_LISTAR_FN
RETURN VARCHAR2;

-- Lista inventario actual
FUNCTION INVENTARIO_LISTAR_FN
RETURN VARCHAR2;

-- Lista facturas registradas
FUNCTION FACTURAS_LISTAR_FN
RETURN VARCHAR2;

-- Lista todas las citas
FUNCTION CITAS_LISTAR_TODAS_FN
RETURN VARCHAR2;

-- Lista métodos de pago activos
FUNCTION METODOS_PAGO_LISTAR_FN
RETURN VARCHAR2;

-- Lista categorías activas
FUNCTION CATEGORIAS_LISTAR_FN
RETURN VARCHAR2;

-- Lista direcciones de usuarios
FUNCTION DIRECCIONES_LISTAR_USUARIOS_FN
RETURN VARCHAR2;

-- Obtiene detalle de un servicio por ID
FUNCTION SERVICIOS_OBTENER_DETALLE_FN(
    P_SERVICIO_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene detalle de un producto por ID
FUNCTION PRODUCTOS_OBTENER_DETALLE_FN(
    P_PRODUCTO_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene detalle de un proveedor por ID
FUNCTION PROVEEDORES_OBTENER_DETALLE_FN(
    P_PROVEEDOR_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene correo de un cliente por ID
FUNCTION CLIENTES_OBTENER_CORREO_FN(
    P_CLIENTE_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene detalle de una cita por ID
FUNCTION CITAS_OBTENER_DETALLE_FN(
    P_CITA_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene cantidad en inventario de un producto
FUNCTION INVENTARIO_OBTENER_CANTIDAD_FN(
    P_PRODUCTO_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene nombre de categoría por ID
FUNCTION CATEGORIAS_OBTENER_NOMBRE_FN(
    P_CATEGORIA_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene correo por ID
FUNCTION CORREOS_OBTENER_CORREO_FN(
    P_CORREO_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene dirección completa de un usuario
FUNCTION DIRECCIONES_OBTENER_DETALLE_FN (
    P_USUARIO_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene teléfono por ID
FUNCTION TELEFONOS_OBTENER_TELEFONO_FN (
    P_TELEFONO_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene nombre de rol por ID
FUNCTION ROLES_OBTENER_NOMBRE_FN (
    P_ROL_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene detalle de factura por ID
FUNCTION FACTURAS_OBTENER_DETALLE_FN (
    P_FACTURA_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene rol de un usuario por ID
FUNCTION USUARIOS_OBTENER_ROL_FN (
    P_USUARIO_ID NUMBER
) RETURN VARCHAR2;

-- Obtiene historial de tratamientos de un cliente
FUNCTION CLIENTES_OBTENER_HISTORIAL_FN (
    P_CLIENTE_ID NUMBER
) RETURN VARCHAR2;

-- =========================
-- PROCEDIMIENTOS
-- =========================

-- CRUD para Estados
PROCEDURE FIDE_ESTADOS_INSERTAR_SP (
  p_estado_id     IN FIDE_ESTADOS_TB.ESTADO_ID%TYPE,
  p_nombre_estado IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
);

PROCEDURE FIDE_ESTADOS_MODIFICAR_SP (
  p_estado_id     IN FIDE_ESTADOS_TB.ESTADO_ID%TYPE,
  p_nombre_estado IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE
);

-- CRUD para Roles
PROCEDURE FIDE_ROLES_INSERTAR_SP (
  p_rol_id     IN FIDE_ROLES_TB.ROL_ID%TYPE,
  p_estado_id  IN FIDE_ROLES_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_nombre_rol IN FIDE_ROLES_TB.NOMBRE_ROL%TYPE
);

PROCEDURE FIDE_ROLES_MODIFICAR_SP (
  p_rol_id     IN FIDE_ROLES_TB.ROL_ID%TYPE,
  p_estado_id  IN FIDE_ROLES_TB.ESTADO_ID%TYPE,
  p_nombre_rol IN FIDE_ROLES_TB.NOMBRE_ROL%TYPE
);

PROCEDURE FIDE_ROLES_ELIMINAR_SP (
  p_rol_id IN FIDE_ROLES_TB.ROL_ID%TYPE
);

-- CRUD para Correos
PROCEDURE FIDE_CORREOS_INSERTAR_SP (
  p_correo_id IN FIDE_CORREOS_TB.CORREO_ID%TYPE,
  p_estado_id IN FIDE_CORREOS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_correo    IN FIDE_CORREOS_TB.CORREO%TYPE
);

PROCEDURE FIDE_CORREOS_MODIFICAR_SP (
  p_correo_id IN FIDE_CORREOS_TB.CORREO_ID%TYPE,
  p_estado_id IN FIDE_CORREOS_TB.ESTADO_ID%TYPE,
  p_correo    IN FIDE_CORREOS_TB.CORREO%TYPE
);

PROCEDURE FIDE_CORREOS_ELIMINAR_SP (
  p_correo_id IN FIDE_CORREOS_TB.CORREO_ID%TYPE
);

-- CRUD para Teléfonos
PROCEDURE FIDE_TELEFONOS_INSERTAR_SP (
  p_telefono_id IN FIDE_TELEFONOS_TB.TELEFONO_ID%TYPE,
  p_estado_id   IN FIDE_TELEFONOS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_telefono    IN FIDE_TELEFONOS_TB.TELEFONO%TYPE
);

PROCEDURE FIDE_TELEFONOS_MODIFICAR_SP (
  p_telefono_id IN FIDE_TELEFONOS_TB.TELEFONO_ID%TYPE,
  p_estado_id   IN FIDE_TELEFONOS_TB.ESTADO_ID%TYPE,
  p_telefono    IN FIDE_TELEFONOS_TB.TELEFONO%TYPE
);

PROCEDURE FIDE_TELEFONOS_ELIMINAR_SP (
  p_telefono_id IN FIDE_TELEFONOS_TB.TELEFONO_ID%TYPE
);

-- CRUD para Usuarios
PROCEDURE FIDE_USUARIOS_INSERTAR_SP (
  p_usuario_id       IN FIDE_USUARIOS_TB.USUARIO_ID%TYPE,
  p_rol_id           IN FIDE_USUARIOS_TB.ROL_ID%TYPE,
  p_correo_id        IN FIDE_USUARIOS_TB.CORREO_ID%TYPE,
  p_telefono_id      IN FIDE_USUARIOS_TB.TELEFONO_ID%TYPE,
  p_estado_id        IN FIDE_USUARIOS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_nombre           IN FIDE_USUARIOS_TB.NOMBRE%TYPE,
  p_apellido_paterno IN FIDE_USUARIOS_TB.APELLIDO_PATERNO%TYPE,
  p_apellido_materno IN FIDE_USUARIOS_TB.APELLIDO_MATERNO%TYPE,
  p_fecha_registro   IN FIDE_USUARIOS_TB.FECHA_REGISTRO%TYPE DEFAULT SYSDATE
);

PROCEDURE FIDE_USUARIOS_MODIFICAR_SP (
  p_usuario_id       IN FIDE_USUARIOS_TB.USUARIO_ID%TYPE,
  p_rol_id           IN FIDE_USUARIOS_TB.ROL_ID%TYPE,
  p_correo_id        IN FIDE_USUARIOS_TB.CORREO_ID%TYPE,
  p_telefono_id      IN FIDE_USUARIOS_TB.TELEFONO_ID%TYPE,
  p_estado_id        IN FIDE_USUARIOS_TB.ESTADO_ID%TYPE,
  p_nombre           IN FIDE_USUARIOS_TB.NOMBRE%TYPE,
  p_apellido_paterno IN FIDE_USUARIOS_TB.APELLIDO_PATERNO%TYPE,
  p_apellido_materno IN FIDE_USUARIOS_TB.APELLIDO_MATERNO%TYPE,
  p_fecha_registro   IN FIDE_USUARIOS_TB.FECHA_REGISTRO%TYPE
);

PROCEDURE FIDE_USUARIOS_ELIMINAR_SP (
  p_usuario_id IN FIDE_USUARIOS_TB.USUARIO_ID%TYPE
);

-- CRUD para Clientes
PROCEDURE FIDE_CLIENTES_INSERTAR_SP (
  p_cliente_id   IN FIDE_CLIENTES_TB.CLIENTE_ID%TYPE,
  p_usuario_id   IN FIDE_CLIENTES_TB.USUARIO_ID%TYPE,
  p_estado_id    IN FIDE_CLIENTES_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_preferencias IN FIDE_CLIENTES_TB.PREFERENCIAS%TYPE,
  p_historial    IN FIDE_CLIENTES_TB.HISTORIAL_TRATAMIENTOS%TYPE
);

PROCEDURE FIDE_CLIENTES_MODIFICAR_SP (
  p_cliente_id   IN FIDE_CLIENTES_TB.CLIENTE_ID%TYPE,
  p_usuario_id   IN FIDE_CLIENTES_TB.USUARIO_ID%TYPE,
  p_estado_id    IN FIDE_CLIENTES_TB.ESTADO_ID%TYPE,
  p_preferencias IN FIDE_CLIENTES_TB.PREFERENCIAS%TYPE,
  p_historial    IN FIDE_CLIENTES_TB.HISTORIAL_TRATAMIENTOS%TYPE
);

PROCEDURE FIDE_CLIENTES_ELIMINAR_SP (
  p_cliente_id IN FIDE_CLIENTES_TB.CLIENTE_ID%TYPE
);

-- CRUD para Provincias
PROCEDURE FIDE_PROVINCIAS_INSERTAR_SP (
  p_provincia_id IN FIDE_PROVINCIAS_TB.PROVINCIA_ID%TYPE,
  p_estado_id    IN FIDE_PROVINCIAS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_nombre       IN FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE
);

PROCEDURE FIDE_PROVINCIAS_MODIFICAR_SP (
  p_provincia_id IN FIDE_PROVINCIAS_TB.PROVINCIA_ID%TYPE,
  p_estado_id    IN FIDE_PROVINCIAS_TB.ESTADO_ID%TYPE,
  p_nombre       IN FIDE_PROVINCIAS_TB.NOMBRE_PROVINCIA%TYPE
);

PROCEDURE FIDE_PROVINCIAS_ELIMINAR_SP (
  p_provincia_id IN FIDE_PROVINCIAS_TB.PROVINCIA_ID%TYPE
);

-- CRUD para Cantones
PROCEDURE FIDE_CANTONES_INSERTAR_SP (
  p_canton_id    IN FIDE_CANTONES_TB.CANTON_ID%TYPE,
  p_provincia_id IN FIDE_CANTONES_TB.PROVINCIA_ID%TYPE,
  p_estado_id    IN FIDE_CANTONES_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_nombre_canton IN FIDE_CANTONES_TB.NOMBRE_CANTON%TYPE
);

PROCEDURE FIDE_CANTONES_MODIFICAR_SP (
  p_canton_id     IN FIDE_CANTONES_TB.CANTON_ID%TYPE,
  p_provincia_id  IN FIDE_CANTONES_TB.PROVINCIA_ID%TYPE,
  p_estado_id     IN FIDE_CANTONES_TB.ESTADO_ID%TYPE,
  p_nombre_canton IN FIDE_CANTONES_TB.NOMBRE_CANTON%TYPE
);

PROCEDURE FIDE_CANTONES_ELIMINAR_SP (
  p_canton_id IN FIDE_CANTONES_TB.CANTON_ID%TYPE
);

-- CRUD para Distritos
PROCEDURE FIDE_DISTRITOS_INSERTAR_SP (
  p_distrito_id    IN FIDE_DISTRITOS_TB.DISTRITO_ID%TYPE,
  p_canton_id      IN FIDE_DISTRITOS_TB.CANTON_ID%TYPE,
  p_estado_id      IN FIDE_DISTRITOS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_nombre_distrito IN FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE
);

PROCEDURE FIDE_DISTRITOS_MODIFICAR_SP (
  p_distrito_id     IN FIDE_DISTRITOS_TB.DISTRITO_ID%TYPE,
  p_canton_id       IN FIDE_DISTRITOS_TB.CANTON_ID%TYPE,
  p_estado_id       IN FIDE_DISTRITOS_TB.ESTADO_ID%TYPE,
  p_nombre_distrito IN FIDE_DISTRITOS_TB.NOMBRE_DISTRITO%TYPE
);

PROCEDURE FIDE_DISTRITOS_ELIMINAR_SP (
  p_distrito_id IN FIDE_DISTRITOS_TB.DISTRITO_ID%TYPE
);

-- CRUD para Direcciones
PROCEDURE FIDE_DIRECCIONES_INSERTAR_SP (
  p_usuario_id  IN FIDE_DIRECCIONES_TB.USUARIO_ID%TYPE,
  p_distrito_id IN FIDE_DIRECCIONES_TB.DISTRITO_ID%TYPE,
  p_estado_id   IN FIDE_DIRECCIONES_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_descripcion IN FIDE_DIRECCIONES_TB.DESCRIPCION%TYPE
);

PROCEDURE FIDE_DIRECCIONES_MODIFICAR_SP (
  p_usuario_id  IN FIDE_DIRECCIONES_TB.USUARIO_ID%TYPE,
  p_distrito_id IN FIDE_DIRECCIONES_TB.DISTRITO_ID%TYPE,
  p_estado_id   IN FIDE_DIRECCIONES_TB.ESTADO_ID%TYPE,
  p_descripcion IN FIDE_DIRECCIONES_TB.DESCRIPCION%TYPE
);

PROCEDURE FIDE_DIRECCIONES_ELIMINAR_SP (
  p_usuario_id  IN FIDE_DIRECCIONES_TB.USUARIO_ID%TYPE,
  p_distrito_id IN FIDE_DIRECCIONES_TB.DISTRITO_ID%TYPE
);

-- CRUD para Categorías
PROCEDURE FIDE_CATEGORIAS_INSERTAR_SP (
  p_categoria_id   IN FIDE_CATEGORIAS_TB.CATEGORIA_ID%TYPE,
  p_estado_id      IN FIDE_CATEGORIAS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_nombre_categoria IN FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE
);

PROCEDURE FIDE_CATEGORIAS_MODIFICAR_SP (
  p_categoria_id    IN FIDE_CATEGORIAS_TB.CATEGORIA_ID%TYPE,
  p_estado_id       IN FIDE_CATEGORIAS_TB.ESTADO_ID%TYPE,
  p_nombre_categoria IN FIDE_CATEGORIAS_TB.NOMBRE_CATEGORIA%TYPE
);

PROCEDURE FIDE_CATEGORIAS_ELIMINAR_SP (
  p_categoria_id IN FIDE_CATEGORIAS_TB.CATEGORIA_ID%TYPE
);

-- CRUD para Servicios
PROCEDURE FIDE_SERVICIOS_INSERTAR_SP (
  p_servicio_id IN FIDE_SERVICIOS_TB.SERVICIO_ID%TYPE,
  p_estado_id   IN FIDE_SERVICIOS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_categoria_id IN FIDE_SERVICIOS_TB.CATEGORIA_ID%TYPE,
  p_nombre      IN FIDE_SERVICIOS_TB.NOMBRE%TYPE,
  p_descripcion IN FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
  p_duracion    IN FIDE_SERVICIOS_TB.DURACION%TYPE,
  p_precio      IN FIDE_SERVICIOS_TB.PRECIO%TYPE,
  p_imagen_url  IN FIDE_SERVICIOS_TB.IMAGEN_URL%TYPE
);

PROCEDURE FIDE_SERVICIOS_MODIFICAR_SP (
  p_servicio_id IN FIDE_SERVICIOS_TB.SERVICIO_ID%TYPE,
  p_estado_id   IN FIDE_SERVICIOS_TB.ESTADO_ID%TYPE,
  p_categoria_id IN FIDE_SERVICIOS_TB.CATEGORIA_ID%TYPE,
  p_nombre      IN FIDE_SERVICIOS_TB.NOMBRE%TYPE,
  p_descripcion IN FIDE_SERVICIOS_TB.DESCRIPCION%TYPE,
  p_duracion    IN FIDE_SERVICIOS_TB.DURACION%TYPE,
  p_precio      IN FIDE_SERVICIOS_TB.PRECIO%TYPE,
  p_imagen_url  IN FIDE_SERVICIOS_TB.IMAGEN_URL%TYPE
);

PROCEDURE FIDE_SERVICIOS_ELIMINAR_SP (
  p_servicio_id IN FIDE_SERVICIOS_TB.SERVICIO_ID%TYPE
);

-- CRUD para Citas
PROCEDURE FIDE_CITAS_INSERTAR_SP (
  p_cliente_id IN FIDE_CITAS_TB.CLIENTE_ID%TYPE,
  p_servicio_id IN FIDE_CITAS_TB.SERVICIO_ID%TYPE,
  p_estado_id  IN FIDE_CITAS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_fecha_hora IN TIMESTAMP,
  p_notas      IN FIDE_CITAS_TB.NOTAS%TYPE
);

PROCEDURE FIDE_CITAS_MODIFICAR_SP (
  p_cita_id    IN FIDE_CITAS_TB.CITA_ID%TYPE,
  p_cliente_id IN FIDE_CITAS_TB.CLIENTE_ID%TYPE,
  p_servicio_id IN FIDE_CITAS_TB.SERVICIO_ID%TYPE,
  p_estado_id  IN FIDE_CITAS_TB.ESTADO_ID%TYPE,
  p_fecha_hora IN FIDE_CITAS_TB.FECHA_HORA%TYPE,
  p_notas      IN FIDE_CITAS_TB.NOTAS%TYPE
);

PROCEDURE FIDE_CITAS_ELIMINAR_SP (
  p_cita_id IN FIDE_CITAS_TB.CITA_ID%TYPE
);

-- CRUD para Proveedores
PROCEDURE FIDE_PROVEEDORES_INSERTAR_SP (
  p_proveedor_id IN FIDE_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
  p_estado_id    IN FIDE_PROVEEDORES_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_telefono_id  IN FIDE_PROVEEDORES_TB.TELEFONO_ID%TYPE,
  p_nombre       IN FIDE_PROVEEDORES_TB.NOMBRE%TYPE,
  p_contacto     IN FIDE_PROVEEDORES_TB.CONTACTO%TYPE
);

PROCEDURE FIDE_PROVEEDORES_MODIFICAR_SP (
  p_proveedor_id IN FIDE_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
  p_estado_id    IN FIDE_PROVEEDORES_TB.ESTADO_ID%TYPE,
  p_telefono_id  IN FIDE_PROVEEDORES_TB.TELEFONO_ID%TYPE,
  p_nombre       IN FIDE_PROVEEDORES_TB.NOMBRE%TYPE,
  p_contacto     IN FIDE_PROVEEDORES_TB.CONTACTO%TYPE
);

PROCEDURE FIDE_PROVEEDORES_ELIMINAR_SP (
  p_proveedor_id IN FIDE_PROVEEDORES_TB.PROVEEDOR_ID%TYPE
);

-- CRUD para Productos
PROCEDURE FIDE_PRODUCTOS_INSERTAR_SP (
  p_producto_id  IN FIDE_PRODUCTOS_TB.PRODUCTO_ID%TYPE,
  p_categoria_id IN FIDE_PRODUCTOS_TB.CATEGORIA_ID%TYPE,
  p_estado_id    IN FIDE_PRODUCTOS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_proveedor_id IN FIDE_PRODUCTOS_TB.PROVEEDOR_ID%TYPE,
  p_nombre       IN FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
  p_descripcion  IN FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
  p_precio       IN FIDE_PRODUCTOS_TB.PRECIO%TYPE,
  p_imagen_url   IN FIDE_PRODUCTOS_TB.IMAGEN_URL%TYPE
);

PROCEDURE FIDE_PRODUCTOS_MODIFICAR_SP (
  p_producto_id  IN FIDE_PRODUCTOS_TB.PRODUCTO_ID%TYPE,
  p_categoria_id IN FIDE_PRODUCTOS_TB.CATEGORIA_ID%TYPE,
  p_estado_id    IN FIDE_PRODUCTOS_TB.ESTADO_ID%TYPE,
  p_proveedor_id IN FIDE_PRODUCTOS_TB.PROVEEDOR_ID%TYPE,
  p_nombre       IN FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
  p_descripcion  IN FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
  p_precio       IN FIDE_PRODUCTOS_TB.PRECIO%TYPE,
  p_imagen_url   IN FIDE_PRODUCTOS_TB.IMAGEN_URL%TYPE
);

PROCEDURE FIDE_PRODUCTOS_ELIMINAR_SP (
  p_producto_id IN FIDE_PRODUCTOS_TB.PRODUCTO_ID%TYPE
);

-- CRUD para Inventario
PROCEDURE FIDE_INVENTARIO_INSERTAR_SP (
  p_producto_id        IN FIDE_INVENTARIO_TB.PRODUCTO_ID%TYPE,
  p_estado_id          IN FIDE_INVENTARIO_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_cantidad           IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
  p_fecha_actualizacion IN FIDE_INVENTARIO_TB.FECHA_ACTUALIZACION%TYPE DEFAULT SYSDATE
);

PROCEDURE FIDE_INVENTARIO_MODIFICAR_SP (
  p_producto_id        IN FIDE_INVENTARIO_TB.PRODUCTO_ID%TYPE,
  p_fecha_actualizacion IN FIDE_INVENTARIO_TB.FECHA_ACTUALIZACION%TYPE,
  p_estado_id          IN FIDE_INVENTARIO_TB.ESTADO_ID%TYPE,
  p_cantidad           IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE
);

PROCEDURE FIDE_INVENTARIO_ELIMINAR_SP (
  p_producto_id        IN FIDE_INVENTARIO_TB.PRODUCTO_ID%TYPE,
  p_fecha_actualizacion IN FIDE_INVENTARIO_TB.FECHA_ACTUALIZACION%TYPE
);

-- CRUD para Métodos de Pago
PROCEDURE FIDE_METODOS_PAGO_INSERTAR_SP (
  p_metodo_pago_id IN FIDE_METODOS_PAGO_TB.METODO_PAGO_ID%TYPE,
  p_estado_id      IN FIDE_METODOS_PAGO_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_nombre_metodo  IN FIDE_METODOS_PAGO_TB.NOMBRE_METODO%TYPE
);

PROCEDURE FIDE_METODOS_PAGO_MODIFICAR_SP (
  p_metodo_pago_id IN FIDE_METODOS_PAGO_TB.METODO_PAGO_ID%TYPE,
  p_estado_id      IN FIDE_METODOS_PAGO_TB.ESTADO_ID%TYPE,
  p_nombre_metodo  IN FIDE_METODOS_PAGO_TB.NOMBRE_METODO%TYPE
);

PROCEDURE FIDE_METODOS_PAGO_ELIMINAR_SP (
  p_metodo_pago_id IN FIDE_METODOS_PAGO_TB.METODO_PAGO_ID%TYPE
);

-- CRUD para Facturas
PROCEDURE FIDE_FACTURAS_INSERTAR_SP (
  p_factura_id     IN FIDE_FACTURAS_TB.FACTURA_ID%TYPE,
  p_cliente_id     IN FIDE_FACTURAS_TB.CLIENTE_ID%TYPE,
  p_estado_id      IN FIDE_FACTURAS_TB.ESTADO_ID%TYPE DEFAULT 1,
  p_metodo_pago_id IN FIDE_FACTURAS_TB.METODO_PAGO_ID%TYPE,
  p_fecha          IN FIDE_FACTURAS_TB.FECHA%TYPE,
  p_impuestos      IN FIDE_FACTURAS_TB.IMPUESTOS%TYPE,
  p_total          IN FIDE_FACTURAS_TB.TOTAL%TYPE
);

PROCEDURE FIDE_FACTURAS_MODIFICAR_SP (
  p_factura_id     IN FIDE_FACTURAS_TB.FACTURA_ID%TYPE,
  p_cliente_id     IN FIDE_FACTURAS_TB.CLIENTE_ID%TYPE,
  p_estado_id      IN FIDE_FACTURAS_TB.ESTADO_ID%TYPE,
  p_metodo_pago_id IN FIDE_FACTURAS_TB.METODO_PAGO_ID%TYPE,
  p_fecha          IN FIDE_FACTURAS_TB.FECHA%TYPE,
  p_impuestos      IN FIDE_FACTURAS_TB.IMPUESTOS%TYPE,
  p_total          IN FIDE_FACTURAS_TB.TOTAL%TYPE
);

PROCEDURE FIDE_FACTURAS_ELIMINAR_SP (
  p_factura_id IN FIDE_FACTURAS_TB.FACTURA_ID%TYPE
);

-- CRUD para Detalles de Factura (versión BODY1)
PROCEDURE FIDE_DETALLES_FACTURA_INSERTAR_SP (
  p_factura_id      IN NUMBER,
  p_producto_id     IN NUMBER,
  p_precio_unitario IN NUMBER,
  p_cantidad        IN NUMBER,
  p_estado_id       IN NUMBER DEFAULT 1
);

PROCEDURE FIDE_DETALLES_FACTURA_MODIFICAR_SP (
  p_factura_id      IN NUMBER,
  p_producto_id     IN NUMBER,
  p_precio_unitario IN NUMBER,
  p_cantidad        IN NUMBER,
  p_estado_id       IN NUMBER
);

PROCEDURE FIDE_DETALLES_FACTURA_ELIMINAR_SP (
  p_factura_id  IN NUMBER,
  p_producto_id IN NUMBER
);

-- CRUD para Direcciones de Proveedores
PROCEDURE FIDE_DIRECCIONES_PROVEEDORES_INSERTAR_SP (
  p_proveedor_id IN FIDE_DIRECCIONES_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
  p_distrito_id  IN FIDE_DIRECCIONES_PROVEEDORES_TB.DISTRITO_ID%TYPE
);

PROCEDURE FIDE_DIRECCIONES_PROVEEDORES_MODIFICAR_SP (
  p_proveedor_id       IN FIDE_DIRECCIONES_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
  p_distrito_id        IN FIDE_DIRECCIONES_PROVEEDORES_TB.DISTRITO_ID%TYPE,
  p_nuevo_proveedor_id IN FIDE_DIRECCIONES_PROVEEDORES_TB.PROVEEDOR_ID%TYPE,
  p_nuevo_distrito_id  IN FIDE_DIRECCIONES_PROVEEDORES_TB.DISTRITO_ID%TYPE
);

-- Procedimientos de Listado
PROCEDURE FIDE_CLIENTES_LISTAR_SP (
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_CLIENTES_OBTENER_SP (
  p_cliente_id IN FIDE_CLIENTES_TB.CLIENTE_ID%TYPE,
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_PRODUCTOS_LISTAR_SP (
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_PRODUCTOS_OBTENER_SP (
  p_producto_id   IN  FIDE_PRODUCTOS_TB.PRODUCTO_ID%TYPE,
  p_categoria_id  OUT FIDE_PRODUCTOS_TB.CATEGORIA_ID%TYPE,
  p_estado_id     OUT FIDE_PRODUCTOS_TB.ESTADO_ID%TYPE,
  p_proveedor_id  OUT FIDE_PRODUCTOS_TB.PROVEEDOR_ID%TYPE,
  p_nombre        OUT FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
  p_descripcion   OUT FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
  p_precio        OUT FIDE_PRODUCTOS_TB.PRECIO%TYPE,
  p_imagen_url    OUT FIDE_PRODUCTOS_TB.IMAGEN_URL%TYPE
);

PROCEDURE FIDE_SERVICIOS_OBTENER_POR_ID_SP (
  p_servicio_id IN FIDE_SERVICIOS_TB.SERVICIO_ID%TYPE,
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_SERVICIOS_OBTENER_TODOS_SP (
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_INVENTARIO_LISTAR_SP (
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_INVENTARIO_OBTENER_SP (
  p_producto_id        IN  FIDE_INVENTARIO_TB.PRODUCTO_ID%TYPE,
  p_fecha_actualizacion IN FIDE_INVENTARIO_TB.FECHA_ACTUALIZACION%TYPE,
  p_estado_id          OUT FIDE_INVENTARIO_TB.ESTADO_ID%TYPE,
  p_cantidad           OUT FIDE_INVENTARIO_TB.CANTIDAD%TYPE
);

PROCEDURE FIDE_PROVEEDORES_LISTAR_SP (
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_PROVEEDORES_OBTENER_SP (
  p_proveedor_id IN NUMBER,
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_USUARIOS_LISTAR_SP (
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_USUARIOS_OBTENER_SP (
  p_usuario_id        IN  FIDE_USUARIOS_TB.USUARIO_ID%TYPE,
  p_rol_id            OUT FIDE_USUARIOS_TB.ROL_ID%TYPE,
  p_correo_id         OUT FIDE_USUARIOS_TB.CORREO_ID%TYPE,
  p_telefono_id       OUT FIDE_USUARIOS_TB.TELEFONO_ID%TYPE,
  p_estado_id         OUT FIDE_USUARIOS_TB.ESTADO_ID%TYPE,
  p_nombre            OUT FIDE_USUARIOS_TB.NOMBRE%TYPE,
  p_apellido_paterno  OUT FIDE_USUARIOS_TB.APELLIDO_PATERNO%TYPE,
  p_apellido_materno  OUT FIDE_USUARIOS_TB.APELLIDO_MATERNO%TYPE,
  p_fecha_registro    OUT FIDE_USUARIOS_TB.FECHA_REGISTRO%TYPE
);

PROCEDURE FIDE_CITAS_LISTAR_SP (
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_CITAS_OBTENER_SP (
  p_cita_id IN FIDE_CITAS_TB.CITA_ID%TYPE,
  p_cursor  OUT SYS_REFCURSOR
);

PROCEDURE FIDE_CATEGORIAS_LISTAR_SP (
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_CATEGORIAS_OBTENER_SP (
  p_categoria_id IN FIDE_CATEGORIAS_TB.CATEGORIA_ID%TYPE,
  p_cursor       OUT SYS_REFCURSOR
);

PROCEDURE FIDE_FACTURAS_LISTAR_SP (
  p_cursor OUT SYS_REFCURSOR
);

PROCEDURE FIDE_FACTURAS_OBTENER_SP (
  p_factura_id IN FIDE_FACTURAS_TB.FACTURA_ID%TYPE,
  p_cursor     OUT SYS_REFCURSOR
);

-- Procedimientos de Autenticación y Registro
PROCEDURE FIDE_USUARIOS_LOGIN_SP (
  p_correo     IN VARCHAR2,
  p_password   IN VARCHAR2,
  p_cursor     OUT SYS_REFCURSOR
);

PROCEDURE FIDE_USUARIOS_REGISTRAR_SP (
  p_nombre            IN VARCHAR2,
  p_apellido_paterno  IN VARCHAR2,
  p_apellido_materno  IN VARCHAR2,
  p_correo            IN VARCHAR2,
  p_telefono          IN VARCHAR2,
  p_password          IN VARCHAR2,
  p_usuario_id        OUT NUMBER,
  p_cliente_id        OUT NUMBER
);

-- Procedimiento de Pago
PROCEDURE FIDE_PAGO_PROCESAR_SP (
  p_cliente_id      IN NUMBER,
  p_metodo_pago_id  IN NUMBER,
  p_items_json      IN CLOB,
  p_factura_id      OUT NUMBER
);


END FIDE_ANGELUS_ESTETICA_PKG;
/