-- Eliminar tablas antiguas
DROP TABLE FIDE_DETALLES_FACTURA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_FACTURAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_INVENTARIO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CITAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DIRECCIONES_PROVEEDORES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DIRECCIONES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PRODUCTOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVEEDORES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_SERVICIOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CLIENTES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_USUARIOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DISTRITOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CANTONES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVINCIAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CATEGORIAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_METODOS_PAGO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CORREOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TELEFONOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ROLES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ESTADOS_TB CASCADE CONSTRAINTS;

---Creación de tablas
CREATE TABLE FIDE_ESTADOS_TB (
    ESTADO_ID NUMBER CONSTRAINT ESTADO_ID_PK PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR2(100) NOT NULL
);

CREATE TABLE FIDE_ROLES_TB (
    ROL_ID NUMBER CONSTRAINT ROL_ID_PK PRIMARY KEY,
    ESTADO_ID NUMBER CONSTRAINT ROL_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    NOMBRE_ROL VARCHAR2(100) NOT NULL
);

CREATE TABLE FIDE_CORREOS_TB (
    CORREO_ID NUMBER CONSTRAINT CORREO_ID_PK PRIMARY KEY,
    ESTADO_ID NUMBER CONSTRAINT CORREO_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    CORREO VARCHAR2(255) NOT NULL UNIQUE
);

CREATE TABLE FIDE_TELEFONOS_TB (
    TELEFONO_ID NUMBER CONSTRAINT TELEFONO_ID_PK PRIMARY KEY,
    ESTADO_ID NUMBER CONSTRAINT TELEFONO_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    TELEFONO VARCHAR2(20) NOT NULL UNIQUE
);

CREATE TABLE FIDE_USUARIOS_TB (
    USUARIO_ID NUMBER CONSTRAINT USUARIO_ID_PK PRIMARY KEY,
    ROL_ID NUMBER CONSTRAINT USUARIO_ROL_ID_FK REFERENCES FIDE_ROLES_TB(ROL_ID),
    CORREO_ID NUMBER CONSTRAINT USUARIO_CORREO_ID_FK REFERENCES FIDE_CORREOS_TB(CORREO_ID),
    TELEFONO_ID NUMBER CONSTRAINT USUARIO_TELEFONO_ID_FK REFERENCES FIDE_TELEFONOS_TB(TELEFONO_ID),
    ESTADO_ID NUMBER CONSTRAINT USUARIO_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(100),
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

CREATE TABLE FIDE_CLIENTES_TB (
    CLIENTE_ID NUMBER CONSTRAINT CLIENTE_ID_PK PRIMARY KEY,
    USUARIO_ID NUMBER CONSTRAINT CLIENTE_USUARIO_ID_FK REFERENCES FIDE_USUARIOS_TB(USUARIO_ID),
    ESTADO_ID NUMBER CONSTRAINT CLIENTE_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    PREFERENCIAS VARCHAR2(4000),
    HISTORIAL_TRATAMIENTOS VARCHAR2(4000)
);

CREATE TABLE FIDE_PROVINCIAS_TB (
    PROVINCIA_ID NUMBER CONSTRAINT PROVINCIA_ID_PK PRIMARY KEY,
    ESTADO_ID NUMBER CONSTRAINT PROVINCIA_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    NOMBRE_PROVINCIA VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE FIDE_CANTONES_TB (
    CANTON_ID NUMBER CONSTRAINT CANTON_ID_PK PRIMARY KEY,
    PROVINCIA_ID NUMBER CONSTRAINT CANTON_PROVINCIA_ID_FK REFERENCES FIDE_PROVINCIAS_TB(PROVINCIA_ID),
    ESTADO_ID NUMBER CONSTRAINT CANTON_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    NOMBRE_CANTON VARCHAR2(100) NOT NULL,
    CONSTRAINT CANTON_UNICO UNIQUE (PROVINCIA_ID, NOMBRE_CANTON)
);

CREATE TABLE FIDE_DISTRITOS_TB (
    DISTRITO_ID NUMBER CONSTRAINT DISTRITO_ID_PK PRIMARY KEY,
    CANTON_ID NUMBER CONSTRAINT DISTRITO_CANTON_ID_FK REFERENCES FIDE_CANTONES_TB(CANTON_ID),
    ESTADO_ID NUMBER CONSTRAINT DISTRITO_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    NOMBRE_DISTRITO VARCHAR2(100) NOT NULL,
    CONSTRAINT DISTRITO_UNICO UNIQUE (CANTON_ID, NOMBRE_DISTRITO)
);

CREATE TABLE FIDE_DIRECCIONES_TB (
    USUARIO_ID NUMBER,
    DISTRITO_ID NUMBER,
    ESTADO_ID NUMBER CONSTRAINT DIRECCION_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT DIRECCION_PK PRIMARY KEY (USUARIO_ID, DISTRITO_ID),
    CONSTRAINT DIRECCION_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID) REFERENCES FIDE_USUARIOS_TB(USUARIO_ID),
    CONSTRAINT DIRECCION_DISTRITO_ID_FK FOREIGN KEY (DISTRITO_ID) REFERENCES FIDE_DISTRITOS_TB(DISTRITO_ID)
);

CREATE TABLE FIDE_CATEGORIAS_TB (
    CATEGORIA_ID NUMBER CONSTRAINT CATEGORIA_ID_PK PRIMARY KEY,
    ESTADO_ID NUMBER CONSTRAINT CATEGORIA_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    NOMBRE_CATEGORIA VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE FIDE_SERVICIOS_TB (
    SERVICIO_ID NUMBER CONSTRAINT SERVICIO_ID_PK PRIMARY KEY,
    ESTADO_ID NUMBER CONSTRAINT SERVICIO_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    CATEGORIA_ID NUMBER CONSTRAINT SERVICIO_CATEGORIA_ID_FK REFERENCES FIDE_CATEGORIAS_TB(CATEGORIA_ID),
    NOMBRE VARCHAR2(200) NOT NULL,
    DESCRIPCION VARCHAR2(4000),
    DURACION NUMBER,
    PRECIO NUMBER(10,2) NOT NULL
);

CREATE TABLE FIDE_CITAS_TB (
    CITA_ID NUMBER,
    CLIENTE_ID NUMBER,
    SERVICIO_ID NUMBER,
    ESTADO_ID NUMBER CONSTRAINT CITA_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    FECHA_HORA TIMESTAMP NOT NULL,
    NOTAS VARCHAR2(4000),
    CONSTRAINT CITA_PK PRIMARY KEY (CLIENTE_ID, SERVICIO_ID, FECHA_HORA),
    CONSTRAINT CITA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID) REFERENCES FIDE_CLIENTES_TB(CLIENTE_ID),
    CONSTRAINT CITA_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID) REFERENCES FIDE_SERVICIOS_TB(SERVICIO_ID)
);

CREATE TABLE FIDE_PROVEEDORES_TB (
    PROVEEDOR_ID NUMBER CONSTRAINT PROVEEDOR_ID_PK PRIMARY KEY,
    ESTADO_ID NUMBER CONSTRAINT PROVEEDOR_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    TELEFONO_ID NUMBER CONSTRAINT PROVEEDOR_TELEFONO_ID_FK REFERENCES FIDE_TELEFONOS_TB(TELEFONO_ID),
    NOMBRE VARCHAR2(200) NOT NULL,
    CONTACTO VARCHAR2(200)
);

CREATE TABLE FIDE_PRODUCTOS_TB (
    PRODUCTO_ID NUMBER CONSTRAINT PRODUCTO_ID_PK PRIMARY KEY,
    CATEGORIA_ID NUMBER CONSTRAINT PRODUCTO_CATEGORIA_ID_FK REFERENCES FIDE_CATEGORIAS_TB(CATEGORIA_ID),
    ESTADO_ID NUMBER CONSTRAINT PRODUCTO_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    PROVEEDOR_ID NUMBER CONSTRAINT PRODUCTO_PROVEEDOR_ID_FK REFERENCES FIDE_PROVEEDORES_TB(PROVEEDOR_ID),
    NOMBRE VARCHAR2(200) NOT NULL,
    DESCRIPCION VARCHAR2(4000),
    PRECIO NUMBER(10,2) NOT NULL
);

CREATE TABLE FIDE_INVENTARIO_TB (
    PRODUCTO_ID NUMBER,
    ESTADO_ID NUMBER CONSTRAINT INVENTARIO_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    CANTIDAD NUMBER NOT NULL,
    FECHA_ACTUALIZACION DATE DEFAULT SYSDATE,
    CONSTRAINT INVENTARIO_PK PRIMARY KEY (PRODUCTO_ID, FECHA_ACTUALIZACION),
    CONSTRAINT INVENTARIO_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID) REFERENCES FIDE_PRODUCTOS_TB(PRODUCTO_ID)
);

CREATE TABLE FIDE_METODOS_PAGO_TB (
    METODO_PAGO_ID NUMBER CONSTRAINT METODO_PAGO_ID_PK PRIMARY KEY,
    ESTADO_ID NUMBER CONSTRAINT METODO_PAGO_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    NOMBRE_METODO VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE FIDE_FACTURAS_TB (
    FACTURA_ID NUMBER CONSTRAINT FACTURA_ID_PK PRIMARY KEY,
    CLIENTE_ID NUMBER CONSTRAINT FACTURA_CLIENTE_ID_FK REFERENCES FIDE_CLIENTES_TB(CLIENTE_ID),
    ESTADO_ID NUMBER CONSTRAINT FACTURA_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    METODO_PAGO_ID NUMBER CONSTRAINT FACTURA_METODO_PAGO_ID_FK REFERENCES FIDE_METODOS_PAGO_TB(METODO_PAGO_ID),
    FECHA DATE DEFAULT SYSDATE,
    IMPUESTOS NUMBER(10,2) DEFAULT 0,
    TOTAL NUMBER(10,2) NOT NULL
);

CREATE TABLE FIDE_DETALLES_FACTURA_TB (
    FACTURA_ID NUMBER,
    SERVICIO_ID NUMBER,
    PRODUCTO_ID NUMBER,
    ESTADO_ID NUMBER CONSTRAINT DETALLE_ESTADO_ID_FK REFERENCES FIDE_ESTADOS_TB(ESTADO_ID),
    PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    CONSTRAINT DETALLE_PK PRIMARY KEY (FACTURA_ID, SERVICIO_ID, PRODUCTO_ID),
    CONSTRAINT DETALLE_FACTURA_ID_FK FOREIGN KEY (FACTURA_ID) REFERENCES FIDE_FACTURAS_TB(FACTURA_ID),
    CONSTRAINT DETALLE_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID) REFERENCES FIDE_SERVICIOS_TB(SERVICIO_ID),
    CONSTRAINT DETALLE_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID) REFERENCES FIDE_PRODUCTOS_TB(PRODUCTO_ID)
);

CREATE TABLE FIDE_DIRECCIONES_PROVEEDORES_TB (
    PROVEEDOR_ID NUMBER,
    DISTRITO_ID NUMBER,
    CONSTRAINT DIR_PROV_PK PRIMARY KEY (PROVEEDOR_ID, DISTRITO_ID),
    CONSTRAINT DIR_PROV_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID) REFERENCES FIDE_PROVEEDORES_TB(PROVEEDOR_ID),
    CONSTRAINT DIR_PROV_DISTRITO_ID_FK FOREIGN KEY (DISTRITO_ID) REFERENCES FIDE_DISTRITOS_TB(DISTRITO_ID)
);

---Cambiar nomenclatura primary keys
ALTER TABLE FIDE_ESTADOS_TB RENAME CONSTRAINT ESTADO_ID_PK TO ESTADOS_ESTADO_ID_PK;
ALTER TABLE FIDE_ROLES_TB RENAME CONSTRAINT ROL_ID_PK TO ROLES_ROL_ID_PK;
ALTER TABLE FIDE_CORREOS_TB RENAME CONSTRAINT CORREO_ID_PK TO CORREOS_CORREO_ID_PK;
ALTER TABLE FIDE_TELEFONOS_TB RENAME CONSTRAINT TELEFONO_ID_PK TO TELEFONOS_TELEFONO_ID_PK;
ALTER TABLE FIDE_USUARIOS_TB RENAME CONSTRAINT USUARIO_ID_PK TO USUARIOS_USUARIO_ID_PK;
ALTER TABLE FIDE_CLIENTES_TB RENAME CONSTRAINT CLIENTE_ID_PK TO CLIENTES_CLIENTE_ID_PK;
ALTER TABLE FIDE_PROVINCIAS_TB RENAME CONSTRAINT PROVINCIA_ID_PK TO PROVINCIAS_PROVINCIA_ID_PK;
ALTER TABLE FIDE_CANTONES_TB RENAME CONSTRAINT CANTON_ID_PK TO CANTONES_CANTON_ID_PK;
ALTER TABLE FIDE_DISTRITOS_TB RENAME CONSTRAINT DISTRITO_ID_PK TO DISTRITOS_DISTRITO_ID_PK;
ALTER TABLE FIDE_DIRECCIONES_TB RENAME CONSTRAINT DIRECCION_PK TO DIRECCIONES_USUARIO_ID_PK;
ALTER TABLE FIDE_CATEGORIAS_TB RENAME CONSTRAINT CATEGORIA_ID_PK TO CATEGORIAS_CATEGORIA_ID_PK;
ALTER TABLE FIDE_SERVICIOS_TB RENAME CONSTRAINT SERVICIO_ID_PK TO SERVICIOS_SERVICIO_ID_PK;
ALTER TABLE FIDE_CITAS_TB RENAME CONSTRAINT CITA_PK TO CITAS_CLIENTE_ID_PK;
ALTER TABLE FIDE_PROVEEDORES_TB RENAME CONSTRAINT PROVEEDOR_ID_PK TO PROVEEDORES_PROVEEDOR_ID_PK;
ALTER TABLE FIDE_PRODUCTOS_TB RENAME CONSTRAINT PRODUCTO_ID_PK TO PRODUCTOS_PRODUCTO_ID_PK;
ALTER TABLE FIDE_INVENTARIO_TB RENAME CONSTRAINT INVENTARIO_PK TO INVENTARIO_PRODUCTO_ID_PK;
ALTER TABLE FIDE_METODOS_PAGO_TB RENAME CONSTRAINT METODO_PAGO_ID_PK TO METODOS_PAGO_METODO_PAGO_ID_PK;
ALTER TABLE FIDE_FACTURAS_TB RENAME CONSTRAINT FACTURA_ID_PK TO FACTURAS_FACTURA_ID_PK;
ALTER TABLE FIDE_DETALLES_FACTURA_TB RENAME CONSTRAINT DETALLE_PK TO DETALLES_FACTURA_FACTURA_ID_PK;
ALTER TABLE FIDE_DIRECCIONES_PROVEEDORES_TB RENAME CONSTRAINT DIR_PROV_PK TO DIRECCIONES_PROVEEDORES_PROVEEDOR_ID_PK;
