---Eliminar vistas antiguas
DROP VIEW FIDE_USUARIOS_ACTIVOS_V;
DROP VIEW FIDE_CLIENTES_COMPLETOS_V;
DROP VIEW FIDE_SERVICIOS_CATEGORIAS_V;
DROP VIEW FIDE_CITAS_PROGRAMADAS_V;
DROP VIEW FIDE_INVENTARIO_PRODUCTOS_V;
DROP VIEW FIDE_DIRECCIONES_COMPLETAS_V;
DROP VIEW FIDE_SERVICIOS_POPULARES_V;
---------------------------------------------------------------------------------------------------
-- Vista para usuarios activos
CREATE OR REPLACE VIEW FIDE_USUARIOS_ACTIVOS_V AS
SELECT 
    u.USUARIO_ID,
    u.NOMBRE,
    u.APELLIDO_PATERNO,
    u.APELLIDO_MATERNO,
    u.FECHA_REGISTRO,
    r.NOMBRE_ROL AS ROL,
    c.CORREO,
    t.TELEFONO,
    e.NOMBRE_ESTADO AS ESTADO
FROM FIDE_USUARIOS_TB u
JOIN FIDE_ROLES_TB r ON u.ROL_ID = r.ROL_ID
JOIN FIDE_CORREOS_TB c ON u.CORREO_ID = c.CORREO_ID
JOIN FIDE_TELEFONOS_TB t ON u.TELEFONO_ID = t.TELEFONO_ID
JOIN FIDE_ESTADOS_TB e ON u.ESTADO_ID = e.ESTADO_ID
WHERE u.ESTADO_ID = 1;
---------------------------------------------------------------------------------------------------
-- Vista para clientes completos
CREATE OR REPLACE VIEW FIDE_CLIENTES_COMPLETOS_V AS
SELECT 
    c.CLIENTE_ID,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO AS NOMBRE_COMPLETO,
    u.FECHA_REGISTRO,
    co.CORREO,
    te.TELEFONO,
    c.PREFERENCIAS,
    c.HISTORIAL_TRATAMIENTOS,
    e.NOMBRE_ESTADO AS ESTADO
FROM FIDE_CLIENTES_TB c
JOIN FIDE_USUARIOS_TB u ON c.USUARIO_ID = u.USUARIO_ID
JOIN FIDE_CORREOS_TB co ON u.CORREO_ID = co.CORREO_ID
JOIN FIDE_TELEFONOS_TB te ON u.TELEFONO_ID = te.TELEFONO_ID
JOIN FIDE_ESTADOS_TB e ON c.ESTADO_ID = e.ESTADO_ID
WHERE c.ESTADO_ID = 1;
---------------------------------------------------------------------------------------------------
-- Vista para servicios con categorías
CREATE OR REPLACE VIEW FIDE_SERVICIOS_CATEGORIAS_V AS
SELECT 
    s.SERVICIO_ID,
    s.NOMBRE AS SERVICIO,
    s.DESCRIPCION,
    s.DURACION,
    s.PRECIO,
    c.NOMBRE_CATEGORIA AS CATEGORIA,
    e.NOMBRE_ESTADO AS ESTADO
FROM FIDE_SERVICIOS_TB s
JOIN FIDE_CATEGORIAS_TB c ON s.CATEGORIA_ID = c.CATEGORIA_ID
JOIN FIDE_ESTADOS_TB e ON s.ESTADO_ID = e.ESTADO_ID
WHERE s.ESTADO_ID = 1;
---------------------------------------------------------------------------------------------------
-- Vista para citas programadas (CORREGIDA - ya no existe CITA_ID como PK individual)
CREATE OR REPLACE VIEW FIDE_CITAS_PROGRAMADAS_V AS
SELECT 
    ci.CLIENTE_ID,
    ci.SERVICIO_ID,
    ci.FECHA_HORA,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO AS CLIENTE,
    s.NOMBRE AS SERVICIO,
    ci.NOTAS,
    es.NOMBRE_ESTADO AS ESTADO_CITA
FROM FIDE_CITAS_TB ci
JOIN FIDE_CLIENTES_TB cl ON ci.CLIENTE_ID = cl.CLIENTE_ID
JOIN FIDE_USUARIOS_TB u ON cl.USUARIO_ID = u.USUARIO_ID
JOIN FIDE_SERVICIOS_TB s ON ci.SERVICIO_ID = s.SERVICIO_ID
JOIN FIDE_ESTADOS_TB es ON ci.ESTADO_ID = es.ESTADO_ID
WHERE ci.ESTADO_ID IN (1, 3); -- Activo y Pendiente
---------------------------------------------------------------------------------------------------
-- Vista para inventario de productos (CORREGIDA - ya no existe INVENTARIO_ID)
CREATE OR REPLACE VIEW FIDE_INVENTARIO_PRODUCTOS_V AS
SELECT 
    i.PRODUCTO_ID,
    p.NOMBRE AS PRODUCTO,
    p.DESCRIPCION,
    p.PRECIO AS PRECIO_VENTA,
    i.CANTIDAD,
    i.FECHA_ACTUALIZACION,
    cat.NOMBRE_CATEGORIA AS CATEGORIA,
    prov.NOMBRE AS PROVEEDOR,
    e.NOMBRE_ESTADO AS ESTADO
FROM FIDE_INVENTARIO_TB i
JOIN FIDE_PRODUCTOS_TB p ON i.PRODUCTO_ID = p.PRODUCTO_ID
JOIN FIDE_CATEGORIAS_TB cat ON p.CATEGORIA_ID = cat.CATEGORIA_ID
JOIN FIDE_PROVEEDORES_TB prov ON p.PROVEEDOR_ID = prov.PROVEEDOR_ID
JOIN FIDE_ESTADOS_TB e ON i.ESTADO_ID = e.ESTADO_ID
WHERE i.ESTADO_ID = 1;
---------------------------------------------------------------------------------------------------
-- Vista para direcciones completas
CREATE OR REPLACE VIEW FIDE_DIRECCIONES_COMPLETAS_V AS
SELECT 
    d.USUARIO_ID,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO AS USUARIO,
    d.DESCRIPCION AS DIRECCION,
    dist.NOMBRE_DISTRITO AS DISTRITO,
    can.NOMBRE_CANTON AS CANTON,
    prov.NOMBRE_PROVINCIA AS PROVINCIA,
    e.NOMBRE_ESTADO AS ESTADO
FROM FIDE_DIRECCIONES_TB d
JOIN FIDE_USUARIOS_TB u ON d.USUARIO_ID = u.USUARIO_ID
JOIN FIDE_DISTRITOS_TB dist ON d.DISTRITO_ID = dist.DISTRITO_ID
JOIN FIDE_CANTONES_TB can ON dist.CANTON_ID = can.CANTON_ID
JOIN FIDE_PROVINCIAS_TB prov ON can.PROVINCIA_ID = prov.PROVINCIA_ID
JOIN FIDE_ESTADOS_TB e ON d.ESTADO_ID = e.ESTADO_ID
WHERE d.ESTADO_ID = 1;
---------------------------------------------------------------------------------------------------
-- Vista para servicios populares (CORREGIDA - adaptada a nuevas estructuras)
CREATE OR REPLACE VIEW FIDE_SERVICIOS_POPULARES_V AS
SELECT 
    s.SERVICIO_ID,
    s.NOMBRE AS SERVICIO,
    cat.NOMBRE_CATEGORIA AS CATEGORIA,
    s.PRECIO,
    COUNT(ci.CLIENTE_ID) AS TOTAL_CITAS,
    COUNT(df.FACTURA_ID) AS TOTAL_VENTAS,
    (COUNT(ci.CLIENTE_ID) + COUNT(df.FACTURA_ID)) AS POPULARIDAD
FROM FIDE_SERVICIOS_TB s
JOIN FIDE_CATEGORIAS_TB cat ON s.CATEGORIA_ID = cat.CATEGORIA_ID
LEFT JOIN FIDE_CITAS_TB ci ON s.SERVICIO_ID = ci.SERVICIO_ID AND ci.ESTADO_ID = 1 -- Activas
LEFT JOIN FIDE_DETALLES_FACTURA_TB df ON s.SERVICIO_ID = df.SERVICIO_ID AND df.ESTADO_ID = 1
WHERE s.ESTADO_ID = 1 -- Servicios activos
GROUP BY s.SERVICIO_ID, s.NOMBRE, cat.NOMBRE_CATEGORIA, s.PRECIO
ORDER BY POPULARIDAD DESC;
---------------------------------------------------------------------------------------------------
-- Vista para facturas completas
CREATE OR REPLACE VIEW FIDE_FACTURAS_COMPLETAS_V AS
SELECT 
    f.FACTURA_ID,
    f.FECHA,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO AS CLIENTE,
    mp.NOMBRE_METODO AS METODO_PAGO,
    f.IMPUESTOS,
    f.TOTAL,
    e.NOMBRE_ESTADO AS ESTADO
FROM FIDE_FACTURAS_TB f
JOIN FIDE_CLIENTES_TB c ON f.CLIENTE_ID = c.CLIENTE_ID
JOIN FIDE_USUARIOS_TB u ON c.USUARIO_ID = u.USUARIO_ID
JOIN FIDE_METODOS_PAGO_TB mp ON f.METODO_PAGO_ID = mp.METODO_PAGO_ID
JOIN FIDE_ESTADOS_TB e ON f.ESTADO_ID = e.ESTADO_ID;
---------------------------------------------------------------------------------------------------
-- Vista para detalles de factura expandidos
CREATE OR REPLACE VIEW FIDE_DETALLES_FACTURA_EXPANDIDOS_V AS
SELECT 
    df.FACTURA_ID,
    df.SERVICIO_ID,
    df.PRODUCTO_ID,
    s.NOMBRE AS SERVICIO,
    p.NOMBRE AS PRODUCTO,
    df.PRECIO_UNITARIO,
    df.CANTIDAD,
    (df.PRECIO_UNITARIO * df.CANTIDAD) AS SUBTOTAL,
    e.NOMBRE_ESTADO AS ESTADO
FROM FIDE_DETALLES_FACTURA_TB df
LEFT JOIN FIDE_SERVICIOS_TB s ON df.SERVICIO_ID = s.SERVICIO_ID
LEFT JOIN FIDE_PRODUCTOS_TB p ON df.PRODUCTO_ID = p.PRODUCTO_ID
JOIN FIDE_ESTADOS_TB e ON df.ESTADO_ID = e.ESTADO_ID;
---------------------------------------------------------------------------------------------------
SELECT * FROM FIDE_USUARIOS_ACTIVOS_V;
SELECT * FROM FIDE_CLIENTES_COMPLETOS_V;
SELECT * FROM FIDE_SERVICIOS_CATEGORIAS_V;
SELECT * FROM FIDE_CITAS_PROGRAMADAS_V;
SELECT * FROM FIDE_INVENTARIO_PRODUCTOS_V;
SELECT * FROM FIDE_DIRECCIONES_COMPLETAS_V;
SELECT * FROM FIDE_SERVICIOS_POPULARES_V;
SELECT * FROM FIDE_FACTURAS_COMPLETAS_V;
SELECT * FROM FIDE_DETALLES_FACTURA_EXPANDIDOS_V;